# Deep_GLOC masked-seed benchmark notebook

这个 notebook 用于在 **你已经生成好的 no-leak split bundles** 上批量运行 **Deep_GLOC**，并自动计算 benchmark 指标。

## 会做什么
1. 遍历 `pyg_split_bundles/<split_id>/pyg_data_no_leak.pt`
2. 对每个 split 运行多次 Deep_GLOC 训练
3. 聚合多次训练得到平均概率
4. 对当前 process 进行候选基因排序
5. 计算以下指标：
   - Recall@20
   - Recall@50
   - Recall@100
   - median rank
   - MRR
   - AUROC
   - AUPRC
6. 输出：
   - 每个 split 的 ranked genes
   - 每个 split 的 metrics
   - 每个 process 的平均 metrics
   - 四个 process 的 macro-average

## 关键说明
- 这里默认**在候选基因集合上**评估，也就是 `is_supervised_seed == 0` 的节点参与排序。
- 这意味着：
  - train seeds 不参与排名
  - held-out seeds 作为隐藏真阳性参与评估
  - 其他非监督节点作为候选负类 / 未标记背景
- 这是 masked-seed recovery 最常见、也最公平的评估方式。

In [1]:
import os
import copy
import random
import warnings
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.metrics import roc_auc_score, average_precision_score
from torch_geometric.nn import GATv2Conv

warnings.filterwarnings("ignore")

In [2]:
# ============================================================
# 1. 路径配置（按你的本地路径修改）
# ============================================================
BENCHMARK_ROOT = r"D:\phd cases\metabolic analysis\code\Deep_GLOC\run_GAT_new\masked_seed_benchmark"

PYG_SPLIT_DIR = os.path.join(BENCHMARK_ROOT, "pyg_split_bundles")
SPLIT_DIR = os.path.join(BENCHMARK_ROOT, "splits")
SUMMARY_DIR = os.path.join(BENCHMARK_ROOT, "summary")

SPLIT_META_FILE = os.path.join(SUMMARY_DIR, "masked_seed_splits_meta.tsv")
SPLIT_LONG_FILE = os.path.join(SUMMARY_DIR, "masked_seed_splits_long.tsv")

OUT_DIR = os.path.join(BENCHMARK_ROOT, "deep_gloc_benchmark_results_all214_run3")
RUN_SUMMARY_DIR = os.path.join(OUT_DIR, "run_summary")
PRED_DIR = os.path.join(OUT_DIR, "predictions")
METRIC_DIR = os.path.join(OUT_DIR, "metrics")

for d in [OUT_DIR, RUN_SUMMARY_DIR, PRED_DIR, METRIC_DIR]:
    os.makedirs(d, exist_ok=True)

# ============================================================
# 2. 训练配置
#    正式跑可用 N_RUNS=20；调试可先改成 3-5
# ============================================================
CONFIG = {
    "hidden_dim": 32,
    "heads_1": 4,
    "heads_2": 1,
    "dropout": 0.25,
    "lr": 1e-3,
    "weight_decay": 1e-4,
    "num_epochs": 250,
    "patience": 30,
    "lambda_orth": 1e-3,
    "use_seed_weight": True,
    "label_smoothing": 0.0
}

N_RUNS = 3
RUN_SEEDS = list(range(2026, 2026 + N_RUNS))

# ============================================================
# 3. 可选筛选
#    PROCESS_SPLIT_LIMITS = None 表示跑全部 214 个 split
#    输出目录已改为新文件夹，不会覆盖测试结果
# ============================================================
ONLY_PROCESSES = None
# 例如：ONLY_PROCESSES = ["Biosynthesis", "Excretion"]

#MAX_SPLITS_PER_PROCESS = None
# 例如：MAX_SPLITS_PER_PROCESS = 2  # 调试时每个过程只跑2个split
PROCESS_SPLIT_LIMITS = None
# 设为 None 表示跑全部 214 个 split；不会覆盖测试结果，因为 OUT_DIR 已改为新目录

In [3]:
# ============================================================
# 4. 基础函数
# ============================================================
def set_seed(seed: int = 2026):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

def parse_split_id(x):
    return str(x).strip()

def load_split_meta():
    if os.path.exists(SPLIT_META_FILE):
        meta_df = pd.read_csv(SPLIT_META_FILE, sep="\t")
        meta_df["split_id"] = meta_df["split_id"].astype(str).map(parse_split_id)
        return meta_df

    # 没有 meta.tsv 时，直接扫描 pyg_split_bundles
    rows = []
    for p in sorted(Path(PYG_SPLIT_DIR).glob("*")):
        if p.is_dir():
            split_id = p.name
            process = split_id.split("__split_")[0] if "__split_" in split_id else split_id.split("_split_")[0]
            rows.append({
                "split_id": split_id,
                "process": process,
                "repeat_id": np.nan,
                "scheme": np.nan
            })
    return pd.DataFrame(rows)

split_meta_df = load_split_meta()
print("split_meta_df shape:", split_meta_df.shape)
display(split_meta_df.head())

split_meta_df shape: (214, 7)

,split_id,process,repeat_id,scheme,n_total,n_train,n_heldout
0,Biosynthesis__split_001,Biosynthesis,1,random_holdout,15,11,4
1,Biosynthesis__split_002,Biosynthesis,2,random_holdout,15,11,4
2,Biosynthesis__split_003,Biosynthesis,3,random_holdout,15,11,4
3,Biosynthesis__split_004,Biosynthesis,4,random_holdout,15,11,4
4,Biosynthesis__split_005,Biosynthesis,5,random_holdout,15,11,4

# ============================================================
# 5. 根据筛选条件选择要跑的 split
# ============================================================
run_meta_df = split_meta_df.copy()

if ONLY_PROCESSES is not None:
    run_meta_df = run_meta_df[run_meta_df["process"].isin(ONLY_PROCESSES)].copy()

if MAX_SPLITS_PER_PROCESS is not None:
    run_meta_df = (
        run_meta_df.sort_values(["process", "repeat_id", "split_id"])
        .groupby("process", as_index=False, group_keys=False)
        .head(MAX_SPLITS_PER_PROCESS)
        .copy()
    )

run_meta_df = run_meta_df.reset_index(drop=True)
print("n_splits_to_run:", run_meta_df.shape[0])
display(run_meta_df.groupby("process")["split_id"].nunique().reset_index(name="n_splits"))

In [4]:
run_meta_df = split_meta_df.copy()

if ONLY_PROCESSES is not None:
    run_meta_df = run_meta_df[run_meta_df["process"].isin(ONLY_PROCESSES)].copy()

if PROCESS_SPLIT_LIMITS is not None:
    keep_parts = []
    for proc, sub in run_meta_df.groupby("process", group_keys=False):
        sub = sub.sort_values(["process", "repeat_id", "split_id"]).copy()
        limit = PROCESS_SPLIT_LIMITS.get(proc, None)
        if limit is None:
            keep_parts.append(sub)
        else:
            keep_parts.append(sub.head(limit))
    run_meta_df = pd.concat(keep_parts, axis=0).copy()

run_meta_df = run_meta_df.sort_values(["process", "repeat_id", "split_id"]).reset_index(drop=True)
print("Output directory:", OUT_DIR)
print("n_splits_to_run:", run_meta_df.shape[0])
display(run_meta_df.groupby("process")["split_id"].nunique().reset_index(name="n_splits"))

Output directory: D:\phd cases\metabolic analysis\code\Deep_GLOC\run_GAT_new\masked_seed_benchmark\deep_gloc_benchmark_results_all214_run3
n_splits_to_run: 214

          process  n_splits
0    Biosynthesis       100
1  Esterification         6
2       Excretion       100
3          Uptake         8

In [5]:
# ============================================================
# 6. 模型定义（沿用你原来的 Deep_GLOC 主训练 notebook）
# ============================================================
class ExpansionGAT(nn.Module):
    def __init__(
        self,
        in_dim,
        edge_dim,
        hidden_dim,
        out_dim=4,
        heads_1=4,
        heads_2=1,
        dropout=0.25
    ):
        super().__init__()
        self.dropout = dropout

        self.gat1 = GATv2Conv(
            in_channels=in_dim,
            out_channels=hidden_dim,
            heads=heads_1,
            concat=True,
            dropout=dropout,
            edge_dim=edge_dim
        )

        self.gat2 = GATv2Conv(
            in_channels=hidden_dim * heads_1,
            out_channels=out_dim,
            heads=heads_2,
            concat=False,
            dropout=dropout,
            edge_dim=edge_dim
        )

    def forward(self, x, edge_index, edge_attr):
        x = self.gat1(x, edge_index, edge_attr)
        x = F.elu(x)
        x = F.dropout(x, p=self.dropout, training=self.training)

        logits = self.gat2(x, edge_index, edge_attr)
        return logits


def orthogonality_loss(logits):
    probs = F.softmax(logits, dim=1)
    gram = probs.T @ probs
    eye = torch.eye(gram.size(0), device=gram.device)
    return torch.norm(gram - eye, p="fro")


def evaluate_supervised(model, data, label_smoothing=0.0):
    model.eval()
    with torch.no_grad():
        logits = model(data.x, data.edge_index, data.edge_attr)
        pred = logits.argmax(dim=1)

        mask = data.supervised_mask
        if int(mask.sum()) == 0:
            return {"loss": np.nan, "acc": np.nan}

        loss = F.cross_entropy(
            logits[mask],
            data.y[mask],
            label_smoothing=label_smoothing
        ).item()

        acc = (pred[mask] == data.y[mask]).float().mean().item()

    return {"loss": loss, "acc": acc}

In [6]:
def train_one_run(data_cpu, process_map, config, run_seed, run_name="run"):
    set_seed(run_seed)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    data = copy.deepcopy(data_cpu).to(device)

    model = ExpansionGAT(
        in_dim=data.x.shape[1],
        edge_dim=data.edge_attr.shape[1],
        hidden_dim=config["hidden_dim"],
        out_dim=len(process_map),
        heads_1=config["heads_1"],
        heads_2=config["heads_2"],
        dropout=config["dropout"]
    ).to(device)

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=config["lr"],
        weight_decay=config["weight_decay"]
    )

    best_state = None
    best_monitor = np.inf
    best_epoch = -1
    wait = 0
    history = []

    for epoch in range(1, config["num_epochs"] + 1):
        model.train()
        optimizer.zero_grad()

        logits = model(data.x, data.edge_index, data.edge_attr)
        mask = data.supervised_mask

        ce_vec = F.cross_entropy(
            logits[mask],
            data.y[mask],
            reduction="none",
            label_smoothing=config["label_smoothing"]
        )

        if config["use_seed_weight"]:
            ce = (ce_vec * data.seed_weight[mask]).mean()
        else:
            ce = ce_vec.mean()

        orth = orthogonality_loss(logits)
        loss = ce + config["lambda_orth"] * orth

        loss.backward()
        optimizer.step()

        monitor = loss.item()
        eval_res = evaluate_supervised(
            model,
            data,
            label_smoothing=config["label_smoothing"]
        )

        history.append({
            "epoch": epoch,
            "supervised_loss": eval_res["loss"],
            "supervised_acc": eval_res["acc"],
            "ce_loss": ce.item(),
            "orth_loss": orth.item(),
            "total_loss": loss.item()
        })

        if monitor < best_monitor:
            best_monitor = monitor
            best_epoch = epoch
            wait = 0
            best_state = copy.deepcopy(model.state_dict())
        else:
            wait += 1

        if wait >= config["patience"]:
            break

    model.load_state_dict(best_state)
    model.eval()

    with torch.no_grad():
        logits = model(data.x, data.edge_index, data.edge_attr)
        prob = F.softmax(logits, dim=1).detach().cpu()
        pred = logits.argmax(dim=1).detach().cpu()

    return {
        "run_name": run_name,
        "seed": run_seed,
        "best_epoch": best_epoch,
        "best_monitor": best_monitor,
        "history": pd.DataFrame(history),
        "prob": prob,
        "pred": pred,
        "supervised_final": evaluate_supervised(
            model,
            data,
            label_smoothing=config["label_smoothing"]
        )
    }

In [7]:
# ============================================================
# 7. 读取单个 split 的 bundle
# ============================================================
def load_bundle_for_split(split_id):
    pt_file = os.path.join(PYG_SPLIT_DIR, split_id, "pyg_data_no_leak.pt")
    if not os.path.exists(pt_file):
        raise FileNotFoundError(f"pt 文件不存在: {pt_file}")

    bundle = torch.load(pt_file, map_location="cpu", weights_only=False)

    data = bundle["data"]
    node_df = bundle["node_df"].copy()
    aux_info = bundle.get("aux_info", {})
    benchmark_info = bundle.get("benchmark_info", {})

    # process_map
    if "process_map" in aux_info:
        process_map = aux_info["process_map"]
    else:
        process_map = {
            "Biosynthesis": 0,
            "Esterification": 1,
            "Excretion": 2,
            "Uptake": 3
        }

    label2process = {v: k for k, v in process_map.items()}
    process_names = [label2process[i] for i in sorted(label2process)]

    # idx2gene / gene2idx
    if "idx2gene" in aux_info:
        idx2gene = aux_info["idx2gene"]
    else:
        idx2gene = {i: str(g) for i, g in enumerate(node_df["ENSGID"].tolist())}

    if "gene2idx" in aux_info:
        gene2idx = aux_info["gene2idx"]
    else:
        gene2idx = {g: i for i, g in idx2gene.items()}

    # edge_attr
    if not hasattr(data, "edge_attr") or data.edge_attr is None:
        if hasattr(data, "edge_weight"):
            data.edge_attr = data.edge_weight.view(-1, 1).float()
        else:
            data.edge_attr = torch.ones(data.edge_index.shape[1], 1, dtype=torch.float32)

    # supervised mask
    if not hasattr(data, "supervised_mask"):
        if hasattr(data, "train_mask"):
            data.supervised_mask = data.train_mask.clone()
        else:
            data.supervised_mask = (data.y >= 0)

    # all_core_mask：尽量保留原始属性
    if not hasattr(data, "all_core_mask"):
        data.all_core_mask = (data.y >= 0)

    # seed weight
    if not hasattr(data, "seed_weight"):
        data.seed_weight = torch.ones(data.num_nodes, dtype=torch.float32)

    if "ENSGID" not in node_df.columns:
        node_df["ENSGID"] = [idx2gene[i] for i in range(len(node_df))]

    # held-out genes
    heldout_path = os.path.join(SPLIT_DIR, split_id, "heldout_seeds.tsv")
    if os.path.exists(heldout_path):
        held_df = pd.read_csv(heldout_path, sep="\t")
        heldout_genes = held_df.iloc[:, 0].astype(str).str.strip().str.split(".").str[0].tolist()
    else:
        heldout_genes = benchmark_info.get("heldout_genes", [])

    return {
        "bundle": bundle,
        "data": data,
        "node_df": node_df,
        "process_map": process_map,
        "label2process": label2process,
        "process_names": process_names,
        "idx2gene": idx2gene,
        "gene2idx": gene2idx,
        "heldout_genes": heldout_genes,
        "benchmark_info": benchmark_info,
        "pt_file": pt_file
    }

In [8]:
# ============================================================
# 8. 预测聚合与指标计算
# ============================================================
def aggregate_predictions(all_results):
    prob_stack = torch.stack([res["prob"] for res in all_results], dim=0)   # [R, N, C]
    pred_stack = torch.stack([res["pred"] for res in all_results], dim=0)   # [R, N]

    mean_prob = prob_stack.mean(dim=0)
    std_prob = prob_stack.std(dim=0)

    mean_pred = mean_prob.argmax(dim=1)
    max_prob, _ = mean_prob.max(dim=1)

    sorted_prob, _ = torch.sort(mean_prob, dim=1, descending=True)
    second_prob = sorted_prob[:, 1]
    margin = max_prob - second_prob

    pred_freq = []
    for i in range(mean_prob.shape[0]):
        cls = int(mean_pred[i].item())
        freq = (pred_stack[:, i] == cls).float().mean().item()
        pred_freq.append(freq)
    pred_freq = torch.tensor(pred_freq, dtype=torch.float32)

    return {
        "prob_stack": prob_stack,
        "pred_stack": pred_stack,
        "mean_prob": mean_prob,
        "std_prob": std_prob,
        "mean_pred": mean_pred,
        "max_prob": max_prob,
        "second_prob": second_prob,
        "margin": margin,
        "pred_freq": pred_freq
    }


def build_prediction_table(split_id, process_name, data, idx2gene, label2process, agg):
    pred_df = pd.DataFrame({
        "split_id": split_id,
        "ENSGID": [idx2gene[i] for i in range(data.num_nodes)],
        "pred_label": agg["mean_pred"].numpy(),
        "pred_process": [label2process[int(x)] for x in agg["mean_pred"].numpy()],
        "mean_max_prob": agg["max_prob"].numpy(),
        "mean_second_prob": agg["second_prob"].numpy(),
        "mean_margin": agg["margin"].numpy(),
        "pred_freq": agg["pred_freq"].numpy(),
        "is_supervised_seed": data.supervised_mask.cpu().numpy().astype(int),
        "is_all_core": data.all_core_mask.cpu().numpy().astype(int),
    })

    for lab, proc in label2process.items():
        pred_df[f"prob_{proc}"] = agg["mean_prob"][:, lab].numpy()
        pred_df[f"prob_sd_{proc}"] = agg["std_prob"][:, lab].numpy()

    # 当前 split 评估用 score
    pred_df["eval_process"] = process_name
    pred_df["eval_score"] = pred_df[f"prob_{process_name}"]

    # 候选集合：不在 supervised seeds 中
    pred_df["is_candidate"] = (pred_df["is_supervised_seed"] == 0).astype(int)

    # 在候选集合内部排序，1 为最高
    cand_df = pred_df[pred_df["is_candidate"] == 1].copy()
    cand_df = cand_df.sort_values(
        ["eval_score", "mean_margin", "pred_freq", "ENSGID"],
        ascending=[False, False, False, True]
    ).reset_index(drop=True)
    cand_df["candidate_rank"] = np.arange(1, cand_df.shape[0] + 1)

    pred_df = pred_df.merge(
        cand_df[["ENSGID", "candidate_rank"]],
        on="ENSGID",
        how="left"
    )

    return pred_df


def compute_metrics_from_pred_df(pred_df, heldout_genes):
    heldout_genes = [str(g).split(".")[0] for g in heldout_genes]
    heldout_genes = sorted(set(heldout_genes))

    cand_df = pred_df[pred_df["is_candidate"] == 1].copy()
    cand_df["is_positive"] = cand_df["ENSGID"].isin(heldout_genes).astype(int)

    n_candidates = cand_df.shape[0]
    n_pos = int(cand_df["is_positive"].sum())
    n_neg = n_candidates - n_pos

    held_ranks = (
        cand_df.loc[cand_df["is_positive"] == 1, "candidate_rank"]
        .dropna()
        .astype(int)
        .tolist()
    )

    def recall_at_k(ranks, k):
        if len(ranks) == 0:
            return np.nan
        return np.mean([r <= k for r in ranks])

    metrics = {
        "n_candidates": n_candidates,
        "n_heldout": n_pos,
        "n_negatives": n_neg,
        "Recall@20": recall_at_k(held_ranks, 20),
        "Recall@50": recall_at_k(held_ranks, 50),
        "Recall@100": recall_at_k(held_ranks, 100),
        "median_rank": float(np.median(held_ranks)) if len(held_ranks) > 0 else np.nan,
        "MRR": float(np.mean([1.0 / r for r in held_ranks])) if len(held_ranks) > 0 else np.nan,
    }

    if n_pos > 0 and n_neg > 0:
        y_true = cand_df["is_positive"].values
        y_score = cand_df["eval_score"].values
        metrics["AUROC"] = roc_auc_score(y_true, y_score)
        metrics["AUPRC"] = average_precision_score(y_true, y_score)
    else:
        metrics["AUROC"] = np.nan
        metrics["AUPRC"] = np.nan

    # 单独输出 held-out rank 表，方便排查
    held_rank_df = cand_df[cand_df["is_positive"] == 1][
        ["ENSGID", "candidate_rank", "eval_score"]
    ].sort_values("candidate_rank").reset_index(drop=True)

    return metrics, held_rank_df

In [9]:
# ============================================================
# 9. 单个 split 跑 Deep_GLOC benchmark
# ============================================================
def run_one_split(split_id, process_name):
    print("=" * 100)
    print("Running split:", split_id, "| process:", process_name)
    print("=" * 100)

    split_start_time = time.time()

    obj = load_bundle_for_split(split_id)
    data = obj["data"]
    process_map = obj["process_map"]
    label2process = obj["label2process"]
    idx2gene = obj["idx2gene"]
    heldout_genes = obj["heldout_genes"]

    print("supervised seeds:", int(data.supervised_mask.sum().item()))
    print("heldout genes:", len(heldout_genes))

    all_results = []
    run_time_rows = []

    for i, run_seed in enumerate(RUN_SEEDS, start=1):
        run_name = f"{split_id}__run_{i:02d}_seed_{run_seed}"
        print(f"  [{i}/{len(RUN_SEEDS)}] {run_name}")

        run_start_time = time.time()

        res = train_one_run(
            data_cpu=data,
            process_map=process_map,
            config=CONFIG,
            run_seed=run_seed,
            run_name=run_name
        )

        run_elapsed = time.time() - run_start_time
        print(f"      finished in {run_elapsed/60:.2f} min ({run_elapsed:.1f} sec)")

        run_time_rows.append({
            "split_id": split_id,
            "process": process_name,
            "run_name": run_name,
            "seed": run_seed,
            "elapsed_sec": run_elapsed,
            "elapsed_min": run_elapsed / 60
        })

        all_results.append(res)

    split_elapsed = time.time() - split_start_time
    print(f"Split {split_id} finished in {split_elapsed/60:.2f} min ({split_elapsed:.1f} sec)")

    # 训练摘要
    train_summary_df = pd.DataFrame([{
        "split_id": split_id,
        "process": process_name,
        "run_name": res["run_name"],
        "seed": res["seed"],
        "best_epoch": res["best_epoch"],
        "best_monitor": res["best_monitor"],
        "supervised_loss": res["supervised_final"]["loss"],
        "supervised_acc": res["supervised_final"]["acc"]
    } for res in all_results])

    # 合并每次 run 的耗时
    run_time_df = pd.DataFrame(run_time_rows)
    train_summary_df = train_summary_df.merge(
        run_time_df,
        on=["split_id", "process", "run_name", "seed"],
        how="left"
    )

    train_summary_file = os.path.join(RUN_SUMMARY_DIR, f"{split_id}__training_summary.tsv")
    train_summary_df.to_csv(train_summary_file, sep="\t", index=False)

    agg = aggregate_predictions(all_results)

    pred_df = build_prediction_table(
        split_id=split_id,
        process_name=process_name,
        data=data,
        idx2gene=idx2gene,
        label2process=label2process,
        agg=agg
    )

    metrics, held_rank_df = compute_metrics_from_pred_df(pred_df, heldout_genes)
    metrics_row = {
        "split_id": split_id,
        "process": process_name,
        "split_elapsed_sec": split_elapsed,
        "split_elapsed_min": split_elapsed / 60,
        **metrics
    }

    pred_file = os.path.join(PRED_DIR, f"{split_id}__ranked_predictions.tsv")
    pred_df.to_csv(pred_file, sep="\t", index=False)

    held_rank_file = os.path.join(PRED_DIR, f"{split_id}__heldout_ranks.tsv")
    held_rank_df.to_csv(held_rank_file, sep="\t", index=False)

    return {
        "split_id": split_id,
        "process": process_name,
        "pred_df": pred_df,
        "train_summary_df": train_summary_df,
        "metrics_row": metrics_row,
        "held_rank_df": held_rank_df,
        "pred_file": pred_file,
        "held_rank_file": held_rank_file,
        "train_summary_file": train_summary_file
    }

In [10]:
# ============================================================
# 10. 批量运行全部 split
# ============================================================
all_metric_rows = []
all_held_rank_rows = []

for _, row in run_meta_df.iterrows():
    split_id = str(row["split_id"])
    process_name = str(row["process"])

    res = run_one_split(split_id, process_name)

    all_metric_rows.append(res["metrics_row"])

    tmp = res["held_rank_df"].copy()
    tmp["split_id"] = split_id
    tmp["process"] = process_name
    all_held_rank_rows.append(tmp)

split_metrics_df = pd.DataFrame(all_metric_rows)
held_rank_all_df = pd.concat(all_held_rank_rows, axis=0, ignore_index=True) if len(all_held_rank_rows) > 0 else pd.DataFrame()

split_metrics_file = os.path.join(METRIC_DIR, "deep_gloc_split_metrics.tsv")
held_rank_all_file = os.path.join(METRIC_DIR, "deep_gloc_all_heldout_ranks.tsv")

split_metrics_df.to_csv(split_metrics_file, sep="\t", index=False)
held_rank_all_df.to_csv(held_rank_all_file, sep="\t", index=False)

print("saved:")
print(split_metrics_file)
print(held_rank_all_file)

display(split_metrics_df.head())

====================================================================================================
Running split: Biosynthesis__split_001 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_001__run_01_seed_2026
      finished in 3.47 min (208.1 sec)
  [2/3] Biosynthesis__split_001__run_02_seed_2027
      finished in 4.46 min (267.9 sec)
  [3/3] Biosynthesis__split_001__run_03_seed_2028
      finished in 6.75 min (405.0 sec)
Split Biosynthesis__split_001 finished in 14.69 min (881.7 sec)
====================================================================================================
Running split: Biosynthesis__split_002 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_002__run_01_seed_2026
      finished in 3.46 min (207.7 sec)
  [2/3] Biosynthesis__split_002__run_02_seed_2027
      finished in 5.92 min (355.0 sec)
  [3/3] Biosynthesis__split_002__run_03_seed_2028
      finished in 6.49 min (389.4 sec)
Split Biosynthesis__split_002 finished in 15.88 min (952.7 sec)
====================================================================================================
Running split: Biosynthesis__split_003 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_003__run_01_seed_2026
      finished in 3.30 min (198.2 sec)
  [2/3] Biosynthesis__split_003__run_02_seed_2027
      finished in 7.18 min (430.9 sec)
  [3/3] Biosynthesis__split_003__run_03_seed_2028
      finished in 4.40 min (263.8 sec)
Split Biosynthesis__split_003 finished in 14.89 min (893.6 sec)
====================================================================================================
Running split: Biosynthesis__split_004 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_004__run_01_seed_2026
      finished in 3.26 min (195.7 sec)
  [2/3] Biosynthesis__split_004__run_02_seed_2027
      finished in 4.28 min (256.6 sec)
  [3/3] Biosynthesis__split_004__run_03_seed_2028
      finished in 4.66 min (279.3 sec)
Split Biosynthesis__split_004 finished in 12.20 min (732.3 sec)
====================================================================================================
Running split: Biosynthesis__split_005 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_005__run_01_seed_2026
      finished in 6.30 min (378.1 sec)
  [2/3] Biosynthesis__split_005__run_02_seed_2027
      finished in 7.19 min (431.3 sec)
  [3/3] Biosynthesis__split_005__run_03_seed_2028
      finished in 4.66 min (279.4 sec)
Split Biosynthesis__split_005 finished in 18.16 min (1089.4 sec)
====================================================================================================
Running split: Biosynthesis__split_006 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_006__run_01_seed_2026
      finished in 3.29 min (197.4 sec)
  [2/3] Biosynthesis__split_006__run_02_seed_2027
      finished in 7.17 min (430.2 sec)
  [3/3] Biosynthesis__split_006__run_03_seed_2028
      finished in 4.41 min (264.4 sec)
Split Biosynthesis__split_006 finished in 14.88 min (892.6 sec)
====================================================================================================
Running split: Biosynthesis__split_007 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_007__run_01_seed_2026
      finished in 3.28 min (196.8 sec)
  [2/3] Biosynthesis__split_007__run_02_seed_2027
      finished in 7.17 min (430.3 sec)
  [3/3] Biosynthesis__split_007__run_03_seed_2028
      finished in 4.42 min (265.1 sec)
Split Biosynthesis__split_007 finished in 14.88 min (892.8 sec)
====================================================================================================
Running split: Biosynthesis__split_008 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_008__run_01_seed_2026
      finished in 6.41 min (384.7 sec)
  [2/3] Biosynthesis__split_008__run_02_seed_2027
      finished in 3.29 min (197.4 sec)
  [3/3] Biosynthesis__split_008__run_03_seed_2028
      finished in 4.73 min (283.9 sec)
Split Biosynthesis__split_008 finished in 14.44 min (866.6 sec)
====================================================================================================
Running split: Biosynthesis__split_009 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_009__run_01_seed_2026
      finished in 6.72 min (403.3 sec)
  [2/3] Biosynthesis__split_009__run_02_seed_2027
      finished in 5.87 min (352.2 sec)
  [3/3] Biosynthesis__split_009__run_03_seed_2028
      finished in 4.60 min (276.1 sec)
Split Biosynthesis__split_009 finished in 17.20 min (1032.2 sec)
====================================================================================================
Running split: Biosynthesis__split_010 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_010__run_01_seed_2026
      finished in 3.26 min (195.7 sec)
  [2/3] Biosynthesis__split_010__run_02_seed_2027
      finished in 7.23 min (433.9 sec)
  [3/3] Biosynthesis__split_010__run_03_seed_2028
      finished in 6.38 min (382.7 sec)
Split Biosynthesis__split_010 finished in 16.88 min (1012.9 sec)
====================================================================================================
Running split: Biosynthesis__split_011 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_011__run_01_seed_2026
      finished in 3.29 min (197.1 sec)
  [2/3] Biosynthesis__split_011__run_02_seed_2027
      finished in 4.28 min (256.5 sec)
  [3/3] Biosynthesis__split_011__run_03_seed_2028
      finished in 6.36 min (381.6 sec)
Split Biosynthesis__split_011 finished in 13.93 min (835.8 sec)
====================================================================================================
Running split: Biosynthesis__split_012 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_012__run_01_seed_2026
      finished in 5.78 min (346.6 sec)
  [2/3] Biosynthesis__split_012__run_02_seed_2027
      finished in 5.57 min (334.2 sec)
  [3/3] Biosynthesis__split_012__run_03_seed_2028
      finished in 6.36 min (381.8 sec)
Split Biosynthesis__split_012 finished in 17.72 min (1063.3 sec)
====================================================================================================
Running split: Biosynthesis__split_013 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_013__run_01_seed_2026
      finished in 3.28 min (196.9 sec)
  [2/3] Biosynthesis__split_013__run_02_seed_2027
      finished in 5.84 min (350.3 sec)
  [3/3] Biosynthesis__split_013__run_03_seed_2028
      finished in 4.57 min (274.3 sec)
Split Biosynthesis__split_013 finished in 13.70 min (822.2 sec)

====================================================================================================
Running split: Biosynthesis__split_014 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_014__run_01_seed_2026
      finished in 3.30 min (198.1 sec)
  [2/3] Biosynthesis__split_014__run_02_seed_2027
      finished in 3.33 min (199.9 sec)
  [3/3] Biosynthesis__split_014__run_03_seed_2028
      finished in 4.66 min (279.8 sec)
Split Biosynthesis__split_014 finished in 11.31 min (678.4 sec)
====================================================================================================
Running split: Biosynthesis__split_015 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_015__run_01_seed_2026
      finished in 3.31 min (198.9 sec)
  [2/3] Biosynthesis__split_015__run_02_seed_2027
      finished in 4.36 min (261.6 sec)
  [3/3] Biosynthesis__split_015__run_03_seed_2028
      finished in 4.77 min (285.9 sec)
Split Biosynthesis__split_015 finished in 12.45 min (746.9 sec)
====================================================================================================
Running split: Biosynthesis__split_016 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_016__run_01_seed_2026
      finished in 3.33 min (199.6 sec)
  [2/3] Biosynthesis__split_016__run_02_seed_2027
      finished in 4.27 min (256.3 sec)
  [3/3] Biosynthesis__split_016__run_03_seed_2028
      finished in 6.33 min (379.5 sec)
Split Biosynthesis__split_016 finished in 13.93 min (836.1 sec)
====================================================================================================
Running split: Biosynthesis__split_017 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_017__run_01_seed_2026
      finished in 3.28 min (196.6 sec)
  [2/3] Biosynthesis__split_017__run_02_seed_2027
      finished in 6.01 min (360.8 sec)
  [3/3] Biosynthesis__split_017__run_03_seed_2028
      finished in 4.60 min (275.9 sec)
Split Biosynthesis__split_017 finished in 13.90 min (833.9 sec)
====================================================================================================
Running split: Biosynthesis__split_018 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_018__run_01_seed_2026
      finished in 4.65 min (278.8 sec)
  [2/3] Biosynthesis__split_018__run_02_seed_2027
      finished in 7.17 min (430.2 sec)
  [3/3] Biosynthesis__split_018__run_03_seed_2028
      finished in 4.42 min (265.1 sec)
Split Biosynthesis__split_018 finished in 16.25 min (974.8 sec)
====================================================================================================
Running split: Biosynthesis__split_019 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_019__run_01_seed_2026
      finished in 3.29 min (197.1 sec)
  [2/3] Biosynthesis__split_019__run_02_seed_2027
      finished in 7.19 min (431.4 sec)
  [3/3] Biosynthesis__split_019__run_03_seed_2028
      finished in 4.39 min (263.6 sec)
Split Biosynthesis__split_019 finished in 14.88 min (892.8 sec)
====================================================================================================
Running split: Biosynthesis__split_020 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_020__run_01_seed_2026
      finished in 3.31 min (198.7 sec)
  [2/3] Biosynthesis__split_020__run_02_seed_2027
      finished in 3.28 min (196.5 sec)
  [3/3] Biosynthesis__split_020__run_03_seed_2028
      finished in 4.39 min (263.4 sec)
Split Biosynthesis__split_020 finished in 10.99 min (659.2 sec)
====================================================================================================
Running split: Biosynthesis__split_021 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_021__run_01_seed_2026
      finished in 3.30 min (198.1 sec)
  [2/3] Biosynthesis__split_021__run_02_seed_2027
      finished in 5.93 min (355.6 sec)
  [3/3] Biosynthesis__split_021__run_03_seed_2028
      finished in 4.69 min (281.4 sec)
Split Biosynthesis__split_021 finished in 13.93 min (835.8 sec)
====================================================================================================
Running split: Biosynthesis__split_022 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_022__run_01_seed_2026
      finished in 3.30 min (198.3 sec)
  [2/3] Biosynthesis__split_022__run_02_seed_2027
      finished in 5.85 min (350.8 sec)
  [3/3] Biosynthesis__split_022__run_03_seed_2028
      finished in 4.60 min (275.8 sec)
Split Biosynthesis__split_022 finished in 13.76 min (825.5 sec)
====================================================================================================
Running split: Biosynthesis__split_023 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_023__run_01_seed_2026
      finished in 3.28 min (196.9 sec)
  [2/3] Biosynthesis__split_023__run_02_seed_2027
      finished in 7.21 min (432.8 sec)
  [3/3] Biosynthesis__split_023__run_03_seed_2028
      finished in 6.42 min (385.4 sec)
Split Biosynthesis__split_023 finished in 16.93 min (1015.8 sec)
====================================================================================================
Running split: Biosynthesis__split_024 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_024__run_01_seed_2026
      finished in 3.31 min (198.8 sec)
  [2/3] Biosynthesis__split_024__run_02_seed_2027
      finished in 4.30 min (257.8 sec)
  [3/3] Biosynthesis__split_024__run_03_seed_2028
      finished in 4.69 min (281.3 sec)
Split Biosynthesis__split_024 finished in 12.31 min (738.6 sec)
====================================================================================================
Running split: Biosynthesis__split_025 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_025__run_01_seed_2026
      finished in 3.30 min (198.2 sec)
  [2/3] Biosynthesis__split_025__run_02_seed_2027
      finished in 6.18 min (370.5 sec)
  [3/3] Biosynthesis__split_025__run_03_seed_2028
      finished in 4.68 min (280.6 sec)
Split Biosynthesis__split_025 finished in 14.17 min (850.0 sec)
====================================================================================================
Running split: Biosynthesis__split_026 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_026__run_01_seed_2026
      finished in 6.44 min (386.1 sec)
  [2/3] Biosynthesis__split_026__run_02_seed_2027
      finished in 7.22 min (433.1 sec)
  [3/3] Biosynthesis__split_026__run_03_seed_2028
      finished in 4.59 min (275.3 sec)
Split Biosynthesis__split_026 finished in 18.25 min (1095.1 sec)

====================================================================================================
Running split: Biosynthesis__split_027 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_027__run_01_seed_2026
      finished in 3.29 min (197.1 sec)
  [2/3] Biosynthesis__split_027__run_02_seed_2027
      finished in 7.18 min (430.8 sec)
  [3/3] Biosynthesis__split_027__run_03_seed_2028
      finished in 4.65 min (278.8 sec)
Split Biosynthesis__split_027 finished in 15.12 min (907.4 sec)
====================================================================================================
Running split: Biosynthesis__split_028 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_028__run_01_seed_2026
      finished in 7.20 min (432.0 sec)
  [2/3] Biosynthesis__split_028__run_02_seed_2027
      finished in 3.29 min (197.3 sec)
  [3/3] Biosynthesis__split_028__run_03_seed_2028
      finished in 4.59 min (275.5 sec)
Split Biosynthesis__split_028 finished in 15.09 min (905.5 sec)
====================================================================================================
Running split: Biosynthesis__split_029 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_029__run_01_seed_2026
      finished in 5.87 min (351.9 sec)
  [2/3] Biosynthesis__split_029__run_02_seed_2027
      finished in 7.19 min (431.4 sec)
  [3/3] Biosynthesis__split_029__run_03_seed_2028
      finished in 4.62 min (277.4 sec)
Split Biosynthesis__split_029 finished in 17.69 min (1061.4 sec)
====================================================================================================
Running split: Biosynthesis__split_030 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_030__run_01_seed_2026
      finished in 6.78 min (406.8 sec)
  [2/3] Biosynthesis__split_030__run_02_seed_2027
      finished in 5.49 min (329.5 sec)
  [3/3] Biosynthesis__split_030__run_03_seed_2028
      finished in 4.60 min (276.1 sec)
Split Biosynthesis__split_030 finished in 16.89 min (1013.1 sec)
====================================================================================================
Running split: Biosynthesis__split_031 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_031__run_01_seed_2026
      finished in 6.78 min (406.7 sec)
  [2/3] Biosynthesis__split_031__run_02_seed_2027
      finished in 3.26 min (195.8 sec)
  [3/3] Biosynthesis__split_031__run_03_seed_2028
      finished in 4.60 min (276.3 sec)
Split Biosynthesis__split_031 finished in 14.66 min (879.6 sec)
====================================================================================================
Running split: Biosynthesis__split_032 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_032__run_01_seed_2026
      finished in 3.29 min (197.3 sec)
  [2/3] Biosynthesis__split_032__run_02_seed_2027
      finished in 7.17 min (430.4 sec)
  [3/3] Biosynthesis__split_032__run_03_seed_2028
      finished in 6.31 min (378.6 sec)
Split Biosynthesis__split_032 finished in 16.78 min (1006.9 sec)
====================================================================================================
Running split: Biosynthesis__split_033 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_033__run_01_seed_2026
      finished in 3.29 min (197.5 sec)
  [2/3] Biosynthesis__split_033__run_02_seed_2027
      finished in 7.19 min (431.1 sec)
  [3/3] Biosynthesis__split_033__run_03_seed_2028
      finished in 4.66 min (279.4 sec)
Split Biosynthesis__split_033 finished in 15.14 min (908.7 sec)
====================================================================================================
Running split: Biosynthesis__split_034 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_034__run_01_seed_2026
      finished in 7.17 min (430.5 sec)
  [2/3] Biosynthesis__split_034__run_02_seed_2027
      finished in 5.82 min (349.2 sec)
  [3/3] Biosynthesis__split_034__run_03_seed_2028
      finished in 4.61 min (276.9 sec)
Split Biosynthesis__split_034 finished in 17.62 min (1057.3 sec)
====================================================================================================
Running split: Biosynthesis__split_035 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_035__run_01_seed_2026
      finished in 6.80 min (408.1 sec)
  [2/3] Biosynthesis__split_035__run_02_seed_2027
      finished in 7.17 min (430.3 sec)
  [3/3] Biosynthesis__split_035__run_03_seed_2028
      finished in 4.60 min (276.3 sec)
Split Biosynthesis__split_035 finished in 18.59 min (1115.4 sec)
====================================================================================================
Running split: Biosynthesis__split_036 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_036__run_01_seed_2026
      finished in 3.27 min (196.3 sec)
  [2/3] Biosynthesis__split_036__run_02_seed_2027
      finished in 7.18 min (430.5 sec)
  [3/3] Biosynthesis__split_036__run_03_seed_2028
      finished in 4.62 min (277.0 sec)
Split Biosynthesis__split_036 finished in 15.07 min (904.5 sec)
====================================================================================================
Running split: Biosynthesis__split_037 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_037__run_01_seed_2026
      finished in 3.30 min (197.9 sec)
  [2/3] Biosynthesis__split_037__run_02_seed_2027
      finished in 7.17 min (430.2 sec)
  [3/3] Biosynthesis__split_037__run_03_seed_2028
      finished in 4.61 min (276.3 sec)
Split Biosynthesis__split_037 finished in 15.08 min (905.0 sec)
====================================================================================================
Running split: Biosynthesis__split_038 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_038__run_01_seed_2026
      finished in 3.27 min (195.9 sec)
  [2/3] Biosynthesis__split_038__run_02_seed_2027
      finished in 3.29 min (197.3 sec)
  [3/3] Biosynthesis__split_038__run_03_seed_2028
      finished in 4.41 min (264.9 sec)
Split Biosynthesis__split_038 finished in 10.98 min (658.9 sec)
====================================================================================================
Running split: Biosynthesis__split_039 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_039__run_01_seed_2026
      finished in 3.29 min (197.4 sec)
  [2/3] Biosynthesis__split_039__run_02_seed_2027
      finished in 4.29 min (257.5 sec)
  [3/3] Biosynthesis__split_039__run_03_seed_2028
      finished in 4.61 min (276.4 sec)
Split Biosynthesis__split_039 finished in 12.20 min (731.9 sec)

====================================================================================================
Running split: Biosynthesis__split_040 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_040__run_01_seed_2026
      finished in 4.62 min (277.4 sec)
  [2/3] Biosynthesis__split_040__run_02_seed_2027
      finished in 6.38 min (382.7 sec)
  [3/3] Biosynthesis__split_040__run_03_seed_2028
      finished in 4.41 min (264.3 sec)
Split Biosynthesis__split_040 finished in 15.42 min (925.1 sec)
====================================================================================================
Running split: Biosynthesis__split_041 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_041__run_01_seed_2026
      finished in 7.19 min (431.3 sec)
  [2/3] Biosynthesis__split_041__run_02_seed_2027
      finished in 4.28 min (256.6 sec)
  [3/3] Biosynthesis__split_041__run_03_seed_2028
      finished in 4.60 min (275.7 sec)
Split Biosynthesis__split_041 finished in 16.07 min (964.3 sec)
====================================================================================================
Running split: Biosynthesis__split_042 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_042__run_01_seed_2026
      finished in 3.28 min (196.8 sec)
  [2/3] Biosynthesis__split_042__run_02_seed_2027
      finished in 6.01 min (360.4 sec)
  [3/3] Biosynthesis__split_042__run_03_seed_2028
      finished in 6.35 min (380.7 sec)
Split Biosynthesis__split_042 finished in 15.64 min (938.5 sec)
====================================================================================================
Running split: Biosynthesis__split_043 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_043__run_01_seed_2026
      finished in 3.27 min (196.2 sec)
  [2/3] Biosynthesis__split_043__run_02_seed_2027
      finished in 5.62 min (337.2 sec)
  [3/3] Biosynthesis__split_043__run_03_seed_2028
      finished in 4.62 min (277.5 sec)
Split Biosynthesis__split_043 finished in 13.52 min (811.4 sec)
====================================================================================================
Running split: Biosynthesis__split_044 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_044__run_01_seed_2026
      finished in 3.28 min (196.9 sec)
  [2/3] Biosynthesis__split_044__run_02_seed_2027
      finished in 4.30 min (258.0 sec)
  [3/3] Biosynthesis__split_044__run_03_seed_2028
      finished in 6.40 min (384.2 sec)
Split Biosynthesis__split_044 finished in 14.00 min (839.9 sec)
====================================================================================================
Running split: Biosynthesis__split_045 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_045__run_01_seed_2026
      finished in 3.30 min (197.8 sec)
  [2/3] Biosynthesis__split_045__run_02_seed_2027
      finished in 4.28 min (257.1 sec)
  [3/3] Biosynthesis__split_045__run_03_seed_2028
      finished in 4.61 min (276.4 sec)
Split Biosynthesis__split_045 finished in 12.20 min (732.0 sec)
====================================================================================================
Running split: Biosynthesis__split_046 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_046__run_01_seed_2026
      finished in 3.27 min (196.2 sec)
  [2/3] Biosynthesis__split_046__run_02_seed_2027
      finished in 7.13 min (428.0 sec)
  [3/3] Biosynthesis__split_046__run_03_seed_2028
      finished in 6.42 min (385.2 sec)
Split Biosynthesis__split_046 finished in 16.84 min (1010.1 sec)
====================================================================================================
Running split: Biosynthesis__split_047 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_047__run_01_seed_2026
      finished in 3.29 min (197.2 sec)
  [2/3] Biosynthesis__split_047__run_02_seed_2027
      finished in 5.81 min (348.5 sec)
  [3/3] Biosynthesis__split_047__run_03_seed_2028
      finished in 6.35 min (381.0 sec)
Split Biosynthesis__split_047 finished in 15.46 min (927.4 sec)
====================================================================================================
Running split: Biosynthesis__split_048 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_048__run_01_seed_2026
      finished in 3.27 min (196.2 sec)
  [2/3] Biosynthesis__split_048__run_02_seed_2027
      finished in 7.19 min (431.4 sec)
  [3/3] Biosynthesis__split_048__run_03_seed_2028
      finished in 4.61 min (276.8 sec)
Split Biosynthesis__split_048 finished in 15.08 min (905.1 sec)
====================================================================================================
Running split: Biosynthesis__split_049 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_049__run_01_seed_2026
      finished in 3.29 min (197.7 sec)
  [2/3] Biosynthesis__split_049__run_02_seed_2027
      finished in 5.81 min (348.7 sec)
  [3/3] Biosynthesis__split_049__run_03_seed_2028
      finished in 4.65 min (279.1 sec)
Split Biosynthesis__split_049 finished in 13.77 min (826.1 sec)
====================================================================================================
Running split: Biosynthesis__split_050 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_050__run_01_seed_2026
      finished in 3.28 min (196.7 sec)
  [2/3] Biosynthesis__split_050__run_02_seed_2027
      finished in 7.19 min (431.4 sec)
  [3/3] Biosynthesis__split_050__run_03_seed_2028
      finished in 6.43 min (386.1 sec)
Split Biosynthesis__split_050 finished in 16.91 min (1014.7 sec)
====================================================================================================
Running split: Biosynthesis__split_051 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_051__run_01_seed_2026
      finished in 3.28 min (196.5 sec)
  [2/3] Biosynthesis__split_051__run_02_seed_2027
      finished in 7.20 min (431.9 sec)
  [3/3] Biosynthesis__split_051__run_03_seed_2028
      finished in 6.36 min (381.8 sec)
Split Biosynthesis__split_051 finished in 16.85 min (1011.0 sec)
====================================================================================================
Running split: Biosynthesis__split_052 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_052__run_01_seed_2026
      finished in 3.29 min (197.2 sec)
  [2/3] Biosynthesis__split_052__run_02_seed_2027
      finished in 7.18 min (430.7 sec)
  [3/3] Biosynthesis__split_052__run_03_seed_2028
      finished in 4.42 min (264.9 sec)
Split Biosynthesis__split_052 finished in 14.89 min (893.4 sec)

====================================================================================================
Running split: Biosynthesis__split_053 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_053__run_01_seed_2026
      finished in 3.30 min (198.2 sec)
  [2/3] Biosynthesis__split_053__run_02_seed_2027
      finished in 4.29 min (257.5 sec)
  [3/3] Biosynthesis__split_053__run_03_seed_2028
      finished in 4.39 min (263.7 sec)
Split Biosynthesis__split_053 finished in 12.00 min (719.9 sec)
====================================================================================================
Running split: Biosynthesis__split_054 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_054__run_01_seed_2026
      finished in 7.19 min (431.5 sec)
  [2/3] Biosynthesis__split_054__run_02_seed_2027
      finished in 3.27 min (196.3 sec)
  [3/3] Biosynthesis__split_054__run_03_seed_2028
      finished in 4.62 min (276.9 sec)
Split Biosynthesis__split_054 finished in 15.09 min (905.4 sec)
====================================================================================================
Running split: Biosynthesis__split_055 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_055__run_01_seed_2026
      finished in 3.30 min (197.7 sec)
  [2/3] Biosynthesis__split_055__run_02_seed_2027
      finished in 6.14 min (368.5 sec)
  [3/3] Biosynthesis__split_055__run_03_seed_2028
      finished in 4.40 min (264.1 sec)
Split Biosynthesis__split_055 finished in 13.85 min (831.1 sec)
====================================================================================================
Running split: Biosynthesis__split_056 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_056__run_01_seed_2026
      finished in 3.28 min (196.9 sec)
  [2/3] Biosynthesis__split_056__run_02_seed_2027
      finished in 7.18 min (430.5 sec)
  [3/3] Biosynthesis__split_056__run_03_seed_2028
      finished in 4.67 min (280.2 sec)
Split Biosynthesis__split_056 finished in 15.14 min (908.4 sec)
====================================================================================================
Running split: Biosynthesis__split_057 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_057__run_01_seed_2026
      finished in 3.39 min (203.3 sec)
  [2/3] Biosynthesis__split_057__run_02_seed_2027
      finished in 7.48 min (448.9 sec)
  [3/3] Biosynthesis__split_057__run_03_seed_2028
      finished in 4.41 min (264.5 sec)
Split Biosynthesis__split_057 finished in 15.29 min (917.3 sec)
====================================================================================================
Running split: Biosynthesis__split_058 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_058__run_01_seed_2026
      finished in 3.30 min (197.7 sec)
  [2/3] Biosynthesis__split_058__run_02_seed_2027
      finished in 7.18 min (430.5 sec)
  [3/3] Biosynthesis__split_058__run_03_seed_2028
      finished in 4.59 min (275.3 sec)
Split Biosynthesis__split_058 finished in 15.07 min (904.2 sec)
====================================================================================================
Running split: Biosynthesis__split_059 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_059__run_01_seed_2026
      finished in 3.29 min (197.5 sec)
  [2/3] Biosynthesis__split_059__run_02_seed_2027
      finished in 5.83 min (349.9 sec)
  [3/3] Biosynthesis__split_059__run_03_seed_2028
      finished in 6.45 min (386.7 sec)
Split Biosynthesis__split_059 finished in 15.58 min (934.8 sec)
====================================================================================================
Running split: Biosynthesis__split_060 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_060__run_01_seed_2026
      finished in 2.86 min (171.5 sec)
  [2/3] Biosynthesis__split_060__run_02_seed_2027
      finished in 4.29 min (257.2 sec)
  [3/3] Biosynthesis__split_060__run_03_seed_2028
      finished in 2.81 min (168.6 sec)
Split Biosynthesis__split_060 finished in 9.97 min (597.9 sec)
====================================================================================================
Running split: Biosynthesis__split_061 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_061__run_01_seed_2026
      finished in 4.19 min (251.6 sec)
  [2/3] Biosynthesis__split_061__run_02_seed_2027
      finished in 3.51 min (210.7 sec)
  [3/3] Biosynthesis__split_061__run_03_seed_2028
      finished in 2.74 min (164.5 sec)
Split Biosynthesis__split_061 finished in 10.45 min (627.1 sec)
====================================================================================================
Running split: Biosynthesis__split_062 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_062__run_01_seed_2026
      finished in 1.96 min (117.7 sec)
  [2/3] Biosynthesis__split_062__run_02_seed_2027
      finished in 1.98 min (118.8 sec)
  [3/3] Biosynthesis__split_062__run_03_seed_2028
      finished in 2.74 min (164.4 sec)
Split Biosynthesis__split_062 finished in 6.69 min (401.2 sec)
====================================================================================================
Running split: Biosynthesis__split_063 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_063__run_01_seed_2026
      finished in 1.97 min (118.5 sec)
  [2/3] Biosynthesis__split_063__run_02_seed_2027
      finished in 4.30 min (257.7 sec)
  [3/3] Biosynthesis__split_063__run_03_seed_2028
      finished in 3.82 min (229.0 sec)
Split Biosynthesis__split_063 finished in 10.09 min (605.6 sec)
====================================================================================================
Running split: Biosynthesis__split_064 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_064__run_01_seed_2026
      finished in 1.96 min (117.9 sec)
  [2/3] Biosynthesis__split_064__run_02_seed_2027
      finished in 2.55 min (153.0 sec)
  [3/3] Biosynthesis__split_064__run_03_seed_2028
      finished in 2.74 min (164.5 sec)
Split Biosynthesis__split_064 finished in 7.26 min (435.7 sec)
====================================================================================================
Running split: Biosynthesis__split_065 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_065__run_01_seed_2026
      finished in 1.98 min (118.9 sec)
  [2/3] Biosynthesis__split_065__run_02_seed_2027
      finished in 1.98 min (118.6 sec)
  [3/3] Biosynthesis__split_065__run_03_seed_2028
      finished in 2.77 min (166.5 sec)
Split Biosynthesis__split_065 finished in 6.74 min (404.3 sec)

====================================================================================================
Running split: Biosynthesis__split_066 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_066__run_01_seed_2026
      finished in 3.92 min (235.4 sec)
  [2/3] Biosynthesis__split_066__run_02_seed_2027
      finished in 4.45 min (267.3 sec)
  [3/3] Biosynthesis__split_066__run_03_seed_2028
      finished in 2.77 min (166.3 sec)
Split Biosynthesis__split_066 finished in 11.15 min (669.2 sec)
====================================================================================================
Running split: Biosynthesis__split_067 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_067__run_01_seed_2026
      finished in 1.96 min (117.5 sec)
  [2/3] Biosynthesis__split_067__run_02_seed_2027
      finished in 4.30 min (257.7 sec)
  [3/3] Biosynthesis__split_067__run_03_seed_2028
      finished in 4.00 min (239.9 sec)
Split Biosynthesis__split_067 finished in 10.26 min (615.4 sec)
====================================================================================================
Running split: Biosynthesis__split_068 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_068__run_01_seed_2026
      finished in 4.33 min (259.8 sec)
  [2/3] Biosynthesis__split_068__run_02_seed_2027
      finished in 4.32 min (259.1 sec)
  [3/3] Biosynthesis__split_068__run_03_seed_2028
      finished in 2.82 min (169.0 sec)
Split Biosynthesis__split_068 finished in 11.47 min (688.2 sec)
====================================================================================================
Running split: Biosynthesis__split_069 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_069__run_01_seed_2026
      finished in 2.80 min (168.2 sec)
  [2/3] Biosynthesis__split_069__run_02_seed_2027
      finished in 4.31 min (258.8 sec)
  [3/3] Biosynthesis__split_069__run_03_seed_2028
      finished in 2.63 min (157.8 sec)
Split Biosynthesis__split_069 finished in 9.75 min (585.1 sec)
====================================================================================================
Running split: Biosynthesis__split_070 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_070__run_01_seed_2026
      finished in 2.02 min (121.1 sec)
  [2/3] Biosynthesis__split_070__run_02_seed_2027
      finished in 3.49 min (209.2 sec)
  [3/3] Biosynthesis__split_070__run_03_seed_2028
      finished in 2.63 min (157.6 sec)
Split Biosynthesis__split_070 finished in 8.14 min (488.2 sec)
====================================================================================================
Running split: Biosynthesis__split_071 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_071__run_01_seed_2026
      finished in 1.99 min (119.2 sec)
  [2/3] Biosynthesis__split_071__run_02_seed_2027
      finished in 3.27 min (196.4 sec)
  [3/3] Biosynthesis__split_071__run_03_seed_2028
      finished in 2.65 min (158.8 sec)
Split Biosynthesis__split_071 finished in 7.91 min (474.7 sec)
====================================================================================================
Running split: Biosynthesis__split_072 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_072__run_01_seed_2026
      finished in 1.97 min (118.0 sec)
  [2/3] Biosynthesis__split_072__run_02_seed_2027
      finished in 1.98 min (118.7 sec)
  [3/3] Biosynthesis__split_072__run_03_seed_2028
      finished in 3.88 min (232.7 sec)
Split Biosynthesis__split_072 finished in 7.83 min (469.8 sec)
====================================================================================================
Running split: Biosynthesis__split_073 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_073__run_01_seed_2026
      finished in 2.05 min (123.2 sec)
  [2/3] Biosynthesis__split_073__run_02_seed_2027
      finished in 3.69 min (221.7 sec)
  [3/3] Biosynthesis__split_073__run_03_seed_2028
      finished in 2.63 min (157.7 sec)
Split Biosynthesis__split_073 finished in 8.38 min (502.9 sec)
====================================================================================================
Running split: Biosynthesis__split_074 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_074__run_01_seed_2026
      finished in 1.95 min (117.3 sec)
  [2/3] Biosynthesis__split_074__run_02_seed_2027
      finished in 2.01 min (120.4 sec)
  [3/3] Biosynthesis__split_074__run_03_seed_2028
      finished in 2.83 min (169.8 sec)
Split Biosynthesis__split_074 finished in 6.80 min (407.8 sec)
====================================================================================================
Running split: Biosynthesis__split_075 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_075__run_01_seed_2026
      finished in 1.97 min (118.5 sec)
  [2/3] Biosynthesis__split_075__run_02_seed_2027
      finished in 3.49 min (209.2 sec)
  [3/3] Biosynthesis__split_075__run_03_seed_2028
      finished in 2.73 min (164.1 sec)
Split Biosynthesis__split_075 finished in 8.20 min (492.2 sec)
====================================================================================================
Running split: Biosynthesis__split_076 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_076__run_01_seed_2026
      finished in 2.01 min (120.4 sec)
  [2/3] Biosynthesis__split_076__run_02_seed_2027
      finished in 3.37 min (202.2 sec)
  [3/3] Biosynthesis__split_076__run_03_seed_2028
      finished in 2.76 min (165.7 sec)
Split Biosynthesis__split_076 finished in 8.14 min (488.6 sec)
====================================================================================================
Running split: Biosynthesis__split_077 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_077__run_01_seed_2026
      finished in 1.95 min (117.2 sec)
  [2/3] Biosynthesis__split_077__run_02_seed_2027
      finished in 3.67 min (220.2 sec)
  [3/3] Biosynthesis__split_077__run_03_seed_2028
      finished in 2.65 min (159.1 sec)
Split Biosynthesis__split_077 finished in 8.28 min (496.8 sec)
====================================================================================================
Running split: Biosynthesis__split_078 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_078__run_01_seed_2026
      finished in 1.95 min (117.2 sec)
  [2/3] Biosynthesis__split_078__run_02_seed_2027
      finished in 4.40 min (264.3 sec)
  [3/3] Biosynthesis__split_078__run_03_seed_2028
      finished in 2.65 min (158.8 sec)
Split Biosynthesis__split_078 finished in 9.01 min (540.7 sec)

====================================================================================================
Running split: Biosynthesis__split_079 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_079__run_01_seed_2026
      finished in 1.96 min (117.5 sec)
  [2/3] Biosynthesis__split_079__run_02_seed_2027
      finished in 4.34 min (260.5 sec)
  [3/3] Biosynthesis__split_079__run_03_seed_2028
      finished in 2.78 min (167.0 sec)
Split Biosynthesis__split_079 finished in 9.09 min (545.3 sec)
====================================================================================================
Running split: Biosynthesis__split_080 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_080__run_01_seed_2026
      finished in 3.98 min (238.9 sec)
  [2/3] Biosynthesis__split_080__run_02_seed_2027
      finished in 4.49 min (269.3 sec)
  [3/3] Biosynthesis__split_080__run_03_seed_2028
      finished in 2.76 min (165.5 sec)
Split Biosynthesis__split_080 finished in 11.24 min (674.1 sec)
====================================================================================================
Running split: Biosynthesis__split_081 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_081__run_01_seed_2026
      finished in 1.99 min (119.5 sec)
  [2/3] Biosynthesis__split_081__run_02_seed_2027
      finished in 4.29 min (257.7 sec)
  [3/3] Biosynthesis__split_081__run_03_seed_2028
      finished in 2.65 min (158.9 sec)
Split Biosynthesis__split_081 finished in 8.94 min (536.4 sec)
====================================================================================================
Running split: Biosynthesis__split_082 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_082__run_01_seed_2026
      finished in 2.00 min (120.2 sec)
  [2/3] Biosynthesis__split_082__run_02_seed_2027
      finished in 4.35 min (260.9 sec)
  [3/3] Biosynthesis__split_082__run_03_seed_2028
      finished in 2.74 min (164.6 sec)
Split Biosynthesis__split_082 finished in 9.10 min (546.1 sec)
====================================================================================================
Running split: Biosynthesis__split_083 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_083__run_01_seed_2026
      finished in 2.00 min (120.3 sec)
  [2/3] Biosynthesis__split_083__run_02_seed_2027
      finished in 4.30 min (258.2 sec)
  [3/3] Biosynthesis__split_083__run_03_seed_2028
      finished in 2.70 min (161.8 sec)
Split Biosynthesis__split_083 finished in 9.01 min (540.6 sec)
====================================================================================================
Running split: Biosynthesis__split_084 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_084__run_01_seed_2026
      finished in 3.88 min (232.9 sec)
  [2/3] Biosynthesis__split_084__run_02_seed_2027
      finished in 4.44 min (266.5 sec)
  [3/3] Biosynthesis__split_084__run_03_seed_2028
      finished in 2.82 min (169.5 sec)
Split Biosynthesis__split_084 finished in 11.15 min (669.2 sec)
====================================================================================================
Running split: Biosynthesis__split_085 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_085__run_01_seed_2026
      finished in 2.02 min (121.2 sec)
  [2/3] Biosynthesis__split_085__run_02_seed_2027
      finished in 4.32 min (259.4 sec)
  [3/3] Biosynthesis__split_085__run_03_seed_2028
      finished in 2.65 min (159.0 sec)
Split Biosynthesis__split_085 finished in 9.00 min (539.9 sec)
====================================================================================================
Running split: Biosynthesis__split_086 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_086__run_01_seed_2026
      finished in 1.95 min (117.2 sec)
  [2/3] Biosynthesis__split_086__run_02_seed_2027
      finished in 4.28 min (256.7 sec)
  [3/3] Biosynthesis__split_086__run_03_seed_2028
      finished in 2.63 min (158.0 sec)
Split Biosynthesis__split_086 finished in 8.87 min (532.2 sec)
====================================================================================================
Running split: Biosynthesis__split_087 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_087__run_01_seed_2026
      finished in 2.01 min (120.8 sec)
  [2/3] Biosynthesis__split_087__run_02_seed_2027
      finished in 4.39 min (263.2 sec)
  [3/3] Biosynthesis__split_087__run_03_seed_2028
      finished in 2.78 min (167.1 sec)
Split Biosynthesis__split_087 finished in 9.19 min (551.5 sec)
====================================================================================================
Running split: Biosynthesis__split_088 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_088__run_01_seed_2026
      finished in 1.98 min (118.6 sec)
  [2/3] Biosynthesis__split_088__run_02_seed_2027
      finished in 4.43 min (265.8 sec)
  [3/3] Biosynthesis__split_088__run_03_seed_2028
      finished in 2.69 min (161.5 sec)
Split Biosynthesis__split_088 finished in 9.10 min (546.1 sec)
====================================================================================================
Running split: Biosynthesis__split_089 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_089__run_01_seed_2026
      finished in 2.02 min (121.5 sec)
  [2/3] Biosynthesis__split_089__run_02_seed_2027
      finished in 3.58 min (214.9 sec)
  [3/3] Biosynthesis__split_089__run_03_seed_2028
      finished in 2.82 min (169.0 sec)
Split Biosynthesis__split_089 finished in 8.43 min (505.8 sec)
====================================================================================================
Running split: Biosynthesis__split_090 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_090__run_01_seed_2026
      finished in 2.01 min (120.6 sec)
  [2/3] Biosynthesis__split_090__run_02_seed_2027
      finished in 2.56 min (153.6 sec)
  [3/3] Biosynthesis__split_090__run_03_seed_2028
      finished in 3.82 min (229.0 sec)
Split Biosynthesis__split_090 finished in 8.39 min (503.5 sec)
====================================================================================================
Running split: Biosynthesis__split_091 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_091__run_01_seed_2026
      finished in 1.99 min (119.2 sec)
  [2/3] Biosynthesis__split_091__run_02_seed_2027
      finished in 2.58 min (154.8 sec)
  [3/3] Biosynthesis__split_091__run_03_seed_2028
      finished in 2.77 min (166.3 sec)
Split Biosynthesis__split_091 finished in 7.34 min (440.6 sec)

====================================================================================================
Running split: Biosynthesis__split_092 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_092__run_01_seed_2026
      finished in 4.19 min (251.4 sec)
  [2/3] Biosynthesis__split_092__run_02_seed_2027
      finished in 2.60 min (156.0 sec)
  [3/3] Biosynthesis__split_092__run_03_seed_2028
      finished in 2.78 min (166.6 sec)
Split Biosynthesis__split_092 finished in 9.57 min (574.4 sec)
====================================================================================================
Running split: Biosynthesis__split_093 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_093__run_01_seed_2026
      finished in 2.02 min (121.3 sec)
  [2/3] Biosynthesis__split_093__run_02_seed_2027
      finished in 4.35 min (260.8 sec)
  [3/3] Biosynthesis__split_093__run_03_seed_2028
      finished in 2.62 min (157.5 sec)
Split Biosynthesis__split_093 finished in 9.00 min (539.9 sec)
====================================================================================================
Running split: Biosynthesis__split_094 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_094__run_01_seed_2026
      finished in 1.97 min (118.1 sec)
  [2/3] Biosynthesis__split_094__run_02_seed_2027
      finished in 3.56 min (213.9 sec)
  [3/3] Biosynthesis__split_094__run_03_seed_2028
      finished in 2.85 min (170.8 sec)
Split Biosynthesis__split_094 finished in 8.38 min (503.0 sec)
====================================================================================================
Running split: Biosynthesis__split_095 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_095__run_01_seed_2026
      finished in 4.14 min (248.3 sec)
  [2/3] Biosynthesis__split_095__run_02_seed_2027
      finished in 4.36 min (261.6 sec)
  [3/3] Biosynthesis__split_095__run_03_seed_2028
      finished in 2.84 min (170.4 sec)
Split Biosynthesis__split_095 finished in 11.34 min (680.6 sec)
====================================================================================================
Running split: Biosynthesis__split_096 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_096__run_01_seed_2026
      finished in 2.03 min (122.1 sec)
  [2/3] Biosynthesis__split_096__run_02_seed_2027
      finished in 2.00 min (119.8 sec)
  [3/3] Biosynthesis__split_096__run_03_seed_2028
      finished in 2.81 min (168.3 sec)
Split Biosynthesis__split_096 finished in 6.84 min (410.6 sec)
====================================================================================================
Running split: Biosynthesis__split_097 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_097__run_01_seed_2026
      finished in 4.51 min (270.7 sec)
  [2/3] Biosynthesis__split_097__run_02_seed_2027
      finished in 4.42 min (265.3 sec)
  [3/3] Biosynthesis__split_097__run_03_seed_2028
      finished in 2.84 min (170.1 sec)
Split Biosynthesis__split_097 finished in 11.77 min (706.5 sec)
====================================================================================================
Running split: Biosynthesis__split_098 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_098__run_01_seed_2026
      finished in 2.04 min (122.3 sec)
  [2/3] Biosynthesis__split_098__run_02_seed_2027
      finished in 4.51 min (270.7 sec)
  [3/3] Biosynthesis__split_098__run_03_seed_2028
      finished in 2.90 min (173.7 sec)
Split Biosynthesis__split_098 finished in 9.45 min (567.0 sec)
====================================================================================================
Running split: Biosynthesis__split_099 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_099__run_01_seed_2026
      finished in 2.00 min (120.1 sec)
  [2/3] Biosynthesis__split_099__run_02_seed_2027
      finished in 4.38 min (262.8 sec)
  [3/3] Biosynthesis__split_099__run_03_seed_2028
      finished in 2.69 min (161.6 sec)
Split Biosynthesis__split_099 finished in 9.08 min (544.9 sec)
====================================================================================================
Running split: Biosynthesis__split_100 | process: Biosynthesis
====================================================================================================
supervised seeds: 35
heldout genes: 4
  [1/3] Biosynthesis__split_100__run_01_seed_2026
      finished in 2.02 min (121.0 sec)
  [2/3] Biosynthesis__split_100__run_02_seed_2027
      finished in 3.34 min (200.3 sec)
  [3/3] Biosynthesis__split_100__run_03_seed_2028
      finished in 2.79 min (167.1 sec)
Split Biosynthesis__split_100 finished in 8.15 min (488.8 sec)
====================================================================================================
Running split: Esterification__split_001 | process: Esterification
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Esterification__split_001__run_01_seed_2026
      finished in 4.30 min (258.2 sec)
  [2/3] Esterification__split_001__run_02_seed_2027
      finished in 4.32 min (259.0 sec)
  [3/3] Esterification__split_001__run_03_seed_2028
      finished in 4.21 min (252.6 sec)
Split Esterification__split_001 finished in 12.84 min (770.1 sec)
====================================================================================================
Running split: Esterification__split_002 | process: Esterification
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Esterification__split_002__run_01_seed_2026
      finished in 4.16 min (249.4 sec)
  [2/3] Esterification__split_002__run_02_seed_2027
      finished in 4.36 min (261.6 sec)
  [3/3] Esterification__split_002__run_03_seed_2028
      finished in 2.83 min (169.9 sec)
Split Esterification__split_002 finished in 11.36 min (681.3 sec)
====================================================================================================
Running split: Esterification__split_003 | process: Esterification
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Esterification__split_003__run_01_seed_2026
      finished in 4.25 min (255.1 sec)
  [2/3] Esterification__split_003__run_02_seed_2027
      finished in 2.69 min (161.7 sec)
  [3/3] Esterification__split_003__run_03_seed_2028
      finished in 2.92 min (175.4 sec)
Split Esterification__split_003 finished in 9.87 min (592.5 sec)
====================================================================================================
Running split: Esterification__split_004 | process: Esterification
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Esterification__split_004__run_01_seed_2026
      finished in 2.06 min (123.4 sec)
  [2/3] Esterification__split_004__run_02_seed_2027
      finished in 4.44 min (266.2 sec)
  [3/3] Esterification__split_004__run_03_seed_2028
      finished in 2.89 min (173.4 sec)
Split Esterification__split_004 finished in 9.39 min (563.3 sec)

====================================================================================================
Running split: Esterification__split_005 | process: Esterification
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Esterification__split_005__run_01_seed_2026
      finished in 4.27 min (256.3 sec)
  [2/3] Esterification__split_005__run_02_seed_2027
      finished in 4.42 min (265.4 sec)
  [3/3] Esterification__split_005__run_03_seed_2028
      finished in 2.81 min (168.7 sec)
Split Esterification__split_005 finished in 11.51 min (690.8 sec)
====================================================================================================
Running split: Esterification__split_006 | process: Esterification
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Esterification__split_006__run_01_seed_2026
      finished in 3.61 min (216.7 sec)
  [2/3] Esterification__split_006__run_02_seed_2027
      finished in 4.49 min (269.3 sec)
  [3/3] Esterification__split_006__run_03_seed_2028
      finished in 2.87 min (172.4 sec)
Split Esterification__split_006 finished in 10.98 min (658.8 sec)
====================================================================================================
Running split: Excretion__split_001 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_001__run_01_seed_2026
      finished in 4.15 min (249.2 sec)
  [2/3] Excretion__split_001__run_02_seed_2027
      finished in 3.03 min (181.5 sec)
  [3/3] Excretion__split_001__run_03_seed_2028
      finished in 1.94 min (116.4 sec)
Split Excretion__split_001 finished in 9.12 min (547.4 sec)
====================================================================================================
Running split: Excretion__split_002 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_002__run_01_seed_2026
      finished in 2.57 min (154.4 sec)
  [2/3] Excretion__split_002__run_02_seed_2027
      finished in 3.01 min (180.8 sec)
  [3/3] Excretion__split_002__run_03_seed_2028
      finished in 2.75 min (164.8 sec)
Split Excretion__split_002 finished in 8.34 min (500.2 sec)
====================================================================================================
Running split: Excretion__split_003 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_003__run_01_seed_2026
      finished in 2.90 min (173.8 sec)
  [2/3] Excretion__split_003__run_02_seed_2027
      finished in 2.76 min (165.5 sec)
  [3/3] Excretion__split_003__run_03_seed_2028
      finished in 1.93 min (115.9 sec)
Split Excretion__split_003 finished in 7.59 min (455.4 sec)
====================================================================================================
Running split: Excretion__split_004 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_004__run_01_seed_2026
      finished in 2.80 min (168.1 sec)
  [2/3] Excretion__split_004__run_02_seed_2027
      finished in 3.07 min (183.9 sec)
  [3/3] Excretion__split_004__run_03_seed_2028
      finished in 1.96 min (117.7 sec)
Split Excretion__split_004 finished in 7.83 min (470.0 sec)
====================================================================================================
Running split: Excretion__split_005 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_005__run_01_seed_2026
      finished in 3.03 min (182.1 sec)
  [2/3] Excretion__split_005__run_02_seed_2027
      finished in 3.11 min (186.6 sec)
  [3/3] Excretion__split_005__run_03_seed_2028
      finished in 1.98 min (119.1 sec)
Split Excretion__split_005 finished in 8.13 min (487.9 sec)
====================================================================================================
Running split: Excretion__split_006 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_006__run_01_seed_2026
      finished in 2.67 min (160.2 sec)
  [2/3] Excretion__split_006__run_02_seed_2027
      finished in 1.37 min (82.4 sec)
  [3/3] Excretion__split_006__run_03_seed_2028
      finished in 1.94 min (116.7 sec)
Split Excretion__split_006 finished in 5.99 min (359.4 sec)
====================================================================================================
Running split: Excretion__split_007 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_007__run_01_seed_2026
      finished in 2.99 min (179.5 sec)
  [2/3] Excretion__split_007__run_02_seed_2027
      finished in 1.36 min (81.8 sec)
  [3/3] Excretion__split_007__run_03_seed_2028
      finished in 1.94 min (116.2 sec)
Split Excretion__split_007 finished in 6.29 min (377.6 sec)
====================================================================================================
Running split: Excretion__split_008 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_008__run_01_seed_2026
      finished in 2.30 min (138.0 sec)
  [2/3] Excretion__split_008__run_02_seed_2027
      finished in 2.97 min (177.9 sec)
  [3/3] Excretion__split_008__run_03_seed_2028
      finished in 1.90 min (113.7 sec)
Split Excretion__split_008 finished in 7.16 min (429.8 sec)
====================================================================================================
Running split: Excretion__split_009 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_009__run_01_seed_2026
      finished in 2.97 min (178.0 sec)
  [2/3] Excretion__split_009__run_02_seed_2027
      finished in 1.36 min (81.6 sec)
  [3/3] Excretion__split_009__run_03_seed_2028
      finished in 2.98 min (178.5 sec)
Split Excretion__split_009 finished in 7.30 min (438.3 sec)
====================================================================================================
Running split: Excretion__split_010 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_010__run_01_seed_2026
      finished in 2.96 min (177.7 sec)
  [2/3] Excretion__split_010__run_02_seed_2027
      finished in 2.96 min (177.8 sec)
  [3/3] Excretion__split_010__run_03_seed_2028
      finished in 1.90 min (113.8 sec)
Split Excretion__split_010 finished in 7.83 min (469.5 sec)
====================================================================================================
Running split: Excretion__split_011 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_011__run_01_seed_2026
      finished in 2.96 min (177.7 sec)
  [2/3] Excretion__split_011__run_02_seed_2027
      finished in 2.97 min (178.4 sec)
  [3/3] Excretion__split_011__run_03_seed_2028
      finished in 2.63 min (157.8 sec)
Split Excretion__split_011 finished in 8.57 min (514.2 sec)
====================================================================================================
Running split: Excretion__split_012 | process: Excretion
====================================================================================================

supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_012__run_01_seed_2026
      finished in 2.98 min (178.7 sec)
  [2/3] Excretion__split_012__run_02_seed_2027
      finished in 2.98 min (178.7 sec)
  [3/3] Excretion__split_012__run_03_seed_2028
      finished in 1.91 min (114.5 sec)
Split Excretion__split_012 finished in 7.87 min (472.1 sec)
====================================================================================================
Running split: Excretion__split_013 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_013__run_01_seed_2026
      finished in 2.85 min (171.3 sec)
  [2/3] Excretion__split_013__run_02_seed_2027
      finished in 2.98 min (178.7 sec)
  [3/3] Excretion__split_013__run_03_seed_2028
      finished in 1.83 min (109.5 sec)
Split Excretion__split_013 finished in 7.66 min (459.6 sec)
====================================================================================================
Running split: Excretion__split_014 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_014__run_01_seed_2026
      finished in 2.69 min (161.4 sec)
  [2/3] Excretion__split_014__run_02_seed_2027
      finished in 2.97 min (178.3 sec)
  [3/3] Excretion__split_014__run_03_seed_2028
      finished in 1.93 min (115.8 sec)
Split Excretion__split_014 finished in 7.60 min (455.8 sec)
====================================================================================================
Running split: Excretion__split_015 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_015__run_01_seed_2026
      finished in 2.97 min (178.4 sec)
  [2/3] Excretion__split_015__run_02_seed_2027
      finished in 2.41 min (144.8 sec)
  [3/3] Excretion__split_015__run_03_seed_2028
      finished in 1.90 min (114.1 sec)
Split Excretion__split_015 finished in 7.29 min (437.4 sec)
====================================================================================================
Running split: Excretion__split_016 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_016__run_01_seed_2026
      finished in 2.43 min (145.7 sec)
  [2/3] Excretion__split_016__run_02_seed_2027
      finished in 2.98 min (178.6 sec)
  [3/3] Excretion__split_016__run_03_seed_2028
      finished in 1.91 min (114.5 sec)
Split Excretion__split_016 finished in 7.32 min (439.0 sec)
====================================================================================================
Running split: Excretion__split_017 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_017__run_01_seed_2026
      finished in 2.30 min (138.1 sec)
  [2/3] Excretion__split_017__run_02_seed_2027
      finished in 2.40 min (144.0 sec)
  [3/3] Excretion__split_017__run_03_seed_2028
      finished in 1.93 min (115.7 sec)
Split Excretion__split_017 finished in 6.63 min (398.0 sec)
====================================================================================================
Running split: Excretion__split_018 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_018__run_01_seed_2026
      finished in 2.29 min (137.4 sec)
  [2/3] Excretion__split_018__run_02_seed_2027
      finished in 2.41 min (144.6 sec)
  [3/3] Excretion__split_018__run_03_seed_2028
      finished in 1.90 min (113.9 sec)
Split Excretion__split_018 finished in 6.60 min (396.1 sec)
====================================================================================================
Running split: Excretion__split_019 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_019__run_01_seed_2026
      finished in 2.29 min (137.3 sec)
  [2/3] Excretion__split_019__run_02_seed_2027
      finished in 2.42 min (144.9 sec)
  [3/3] Excretion__split_019__run_03_seed_2028
      finished in 1.94 min (116.4 sec)
Split Excretion__split_019 finished in 6.65 min (398.9 sec)
====================================================================================================
Running split: Excretion__split_020 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_020__run_01_seed_2026
      finished in 2.97 min (178.1 sec)
  [2/3] Excretion__split_020__run_02_seed_2027
      finished in 2.98 min (178.7 sec)
  [3/3] Excretion__split_020__run_03_seed_2028
      finished in 1.91 min (114.7 sec)
Split Excretion__split_020 finished in 7.86 min (471.7 sec)
====================================================================================================
Running split: Excretion__split_021 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_021__run_01_seed_2026
      finished in 2.97 min (178.0 sec)
  [2/3] Excretion__split_021__run_02_seed_2027
      finished in 1.36 min (81.7 sec)
  [3/3] Excretion__split_021__run_03_seed_2028
      finished in 1.91 min (114.5 sec)
Split Excretion__split_021 finished in 6.24 min (374.3 sec)
====================================================================================================
Running split: Excretion__split_022 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_022__run_01_seed_2026
      finished in 2.96 min (177.8 sec)
  [2/3] Excretion__split_022__run_02_seed_2027
      finished in 2.41 min (144.5 sec)
  [3/3] Excretion__split_022__run_03_seed_2028
      finished in 2.97 min (178.1 sec)
Split Excretion__split_022 finished in 8.34 min (500.6 sec)
====================================================================================================
Running split: Excretion__split_023 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_023__run_01_seed_2026
      finished in 2.82 min (168.9 sec)
  [2/3] Excretion__split_023__run_02_seed_2027
      finished in 2.50 min (150.0 sec)
  [3/3] Excretion__split_023__run_03_seed_2028
      finished in 1.96 min (117.7 sec)
Split Excretion__split_023 finished in 7.28 min (436.8 sec)
====================================================================================================
Running split: Excretion__split_024 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_024__run_01_seed_2026
      finished in 3.02 min (181.1 sec)
  [2/3] Excretion__split_024__run_02_seed_2027
      finished in 2.97 min (178.1 sec)
  [3/3] Excretion__split_024__run_03_seed_2028
      finished in 1.90 min (114.3 sec)
Split Excretion__split_024 finished in 7.89 min (473.6 sec)
====================================================================================================
Running split: Excretion__split_025 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_025__run_01_seed_2026
      finished in 2.86 min (171.7 sec)
  [2/3] Excretion__split_025__run_02_seed_2027
      finished in 1.36 min (81.4 sec)
  [3/3] Excretion__split_025__run_03_seed_2028

      finished in 1.95 min (116.8 sec)
Split Excretion__split_025 finished in 6.17 min (370.1 sec)
====================================================================================================
Running split: Excretion__split_026 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_026__run_01_seed_2026
      finished in 2.99 min (179.6 sec)
  [2/3] Excretion__split_026__run_02_seed_2027
      finished in 2.97 min (178.4 sec)
  [3/3] Excretion__split_026__run_03_seed_2028
      finished in 1.90 min (114.0 sec)
Split Excretion__split_026 finished in 7.87 min (472.2 sec)
====================================================================================================
Running split: Excretion__split_027 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_027__run_01_seed_2026
      finished in 3.07 min (184.1 sec)
  [2/3] Excretion__split_027__run_02_seed_2027
      finished in 3.07 min (183.9 sec)
  [3/3] Excretion__split_027__run_03_seed_2028
      finished in 2.73 min (163.6 sec)
Split Excretion__split_027 finished in 8.86 min (531.8 sec)
====================================================================================================
Running split: Excretion__split_028 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_028__run_01_seed_2026
      finished in 2.80 min (168.0 sec)
  [2/3] Excretion__split_028__run_02_seed_2027
      finished in 2.99 min (179.7 sec)
  [3/3] Excretion__split_028__run_03_seed_2028
      finished in 1.95 min (116.9 sec)
Split Excretion__split_028 finished in 7.75 min (464.9 sec)
====================================================================================================
Running split: Excretion__split_029 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_029__run_01_seed_2026
      finished in 2.30 min (138.2 sec)
  [2/3] Excretion__split_029__run_02_seed_2027
      finished in 2.49 min (149.1 sec)
  [3/3] Excretion__split_029__run_03_seed_2028
      finished in 1.92 min (115.5 sec)
Split Excretion__split_029 finished in 6.72 min (402.9 sec)
====================================================================================================
Running split: Excretion__split_030 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_030__run_01_seed_2026
      finished in 3.02 min (181.1 sec)
  [2/3] Excretion__split_030__run_02_seed_2027
      finished in 1.37 min (81.9 sec)
  [3/3] Excretion__split_030__run_03_seed_2028
      finished in 1.93 min (116.0 sec)
Split Excretion__split_030 finished in 6.32 min (379.2 sec)
====================================================================================================
Running split: Excretion__split_031 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_031__run_01_seed_2026
      finished in 2.93 min (175.5 sec)
  [2/3] Excretion__split_031__run_02_seed_2027
      finished in 3.03 min (181.9 sec)
  [3/3] Excretion__split_031__run_03_seed_2028
      finished in 1.86 min (111.3 sec)
Split Excretion__split_031 finished in 7.82 min (469.0 sec)
====================================================================================================
Running split: Excretion__split_032 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_032__run_01_seed_2026
      finished in 2.35 min (141.3 sec)
  [2/3] Excretion__split_032__run_02_seed_2027
      finished in 2.44 min (146.5 sec)
  [3/3] Excretion__split_032__run_03_seed_2028
      finished in 1.94 min (116.2 sec)
Split Excretion__split_032 finished in 6.73 min (404.1 sec)
====================================================================================================
Running split: Excretion__split_033 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_033__run_01_seed_2026
      finished in 2.33 min (139.8 sec)
  [2/3] Excretion__split_033__run_02_seed_2027
      finished in 3.06 min (183.5 sec)
  [3/3] Excretion__split_033__run_03_seed_2028
      finished in 1.94 min (116.4 sec)
Split Excretion__split_033 finished in 7.33 min (440.0 sec)
====================================================================================================
Running split: Excretion__split_034 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_034__run_01_seed_2026
      finished in 3.06 min (183.9 sec)
  [2/3] Excretion__split_034__run_02_seed_2027
      finished in 1.40 min (84.3 sec)
  [3/3] Excretion__split_034__run_03_seed_2028
      finished in 1.93 min (116.0 sec)
Split Excretion__split_034 finished in 6.40 min (384.3 sec)
====================================================================================================
Running split: Excretion__split_035 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_035__run_01_seed_2026
      finished in 3.02 min (181.5 sec)
  [2/3] Excretion__split_035__run_02_seed_2027
      finished in 1.85 min (110.9 sec)
  [3/3] Excretion__split_035__run_03_seed_2028
      finished in 1.96 min (117.8 sec)
Split Excretion__split_035 finished in 6.84 min (410.3 sec)
====================================================================================================
Running split: Excretion__split_036 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_036__run_01_seed_2026
      finished in 2.89 min (173.5 sec)
  [2/3] Excretion__split_036__run_02_seed_2027
      finished in 3.01 min (180.7 sec)
  [3/3] Excretion__split_036__run_03_seed_2028
      finished in 1.96 min (117.8 sec)
Split Excretion__split_036 finished in 7.87 min (472.2 sec)
====================================================================================================
Running split: Excretion__split_037 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_037__run_01_seed_2026
      finished in 3.04 min (182.3 sec)
  [2/3] Excretion__split_037__run_02_seed_2027
      finished in 3.02 min (181.2 sec)
  [3/3] Excretion__split_037__run_03_seed_2028
      finished in 1.94 min (116.6 sec)
Split Excretion__split_037 finished in 8.01 min (480.4 sec)
====================================================================================================
Running split: Excretion__split_038 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_038__run_01_seed_2026
      finished in 3.01 min (180.8 sec)
  [2/3] Excretion__split_038__run_02_seed_2027
      finished in 1.37 min (82.2 sec)
  [3/3] Excretion__split_038__run_03_seed_2028
      finished in 1.95 min (116.8 sec)
Split Excretion__split_038 finished in 6.33 min (380.1 sec)
====================================================================================================
Running split: Excretion__split_039 | process: Excretion
====================================================================================================

supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_039__run_01_seed_2026
      finished in 3.00 min (180.2 sec)
  [2/3] Excretion__split_039__run_02_seed_2027
      finished in 3.01 min (180.5 sec)
  [3/3] Excretion__split_039__run_03_seed_2028
      finished in 1.92 min (115.4 sec)
Split Excretion__split_039 finished in 7.94 min (476.4 sec)
====================================================================================================
Running split: Excretion__split_040 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_040__run_01_seed_2026
      finished in 2.99 min (179.3 sec)
  [2/3] Excretion__split_040__run_02_seed_2027
      finished in 2.44 min (146.5 sec)
  [3/3] Excretion__split_040__run_03_seed_2028
      finished in 2.68 min (160.5 sec)
Split Excretion__split_040 finished in 8.11 min (486.5 sec)
====================================================================================================
Running split: Excretion__split_041 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_041__run_01_seed_2026
      finished in 2.34 min (140.5 sec)
  [2/3] Excretion__split_041__run_02_seed_2027
      finished in 3.00 min (179.9 sec)
  [3/3] Excretion__split_041__run_03_seed_2028
      finished in 1.93 min (115.5 sec)
Split Excretion__split_041 finished in 7.27 min (436.1 sec)
====================================================================================================
Running split: Excretion__split_042 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_042__run_01_seed_2026
      finished in 3.00 min (180.0 sec)
  [2/3] Excretion__split_042__run_02_seed_2027
      finished in 1.36 min (81.5 sec)
  [3/3] Excretion__split_042__run_03_seed_2028
      finished in 1.92 min (114.9 sec)
Split Excretion__split_042 finished in 6.28 min (376.6 sec)
====================================================================================================
Running split: Excretion__split_043 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_043__run_01_seed_2026
      finished in 2.99 min (179.2 sec)
  [2/3] Excretion__split_043__run_02_seed_2027
      finished in 3.00 min (179.7 sec)
  [3/3] Excretion__split_043__run_03_seed_2028
      finished in 2.85 min (170.9 sec)
Split Excretion__split_043 finished in 8.83 min (530.1 sec)
====================================================================================================
Running split: Excretion__split_044 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_044__run_01_seed_2026
      finished in 2.98 min (178.7 sec)
  [2/3] Excretion__split_044__run_02_seed_2027
      finished in 1.36 min (81.4 sec)
  [3/3] Excretion__split_044__run_03_seed_2028
      finished in 1.92 min (115.4 sec)
Split Excretion__split_044 finished in 6.26 min (375.7 sec)
====================================================================================================
Running split: Excretion__split_045 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_045__run_01_seed_2026
      finished in 3.00 min (180.0 sec)
  [2/3] Excretion__split_045__run_02_seed_2027
      finished in 3.03 min (181.6 sec)
  [3/3] Excretion__split_045__run_03_seed_2028
      finished in 1.98 min (118.7 sec)
Split Excretion__split_045 finished in 8.01 min (480.5 sec)
====================================================================================================
Running split: Excretion__split_046 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_046__run_01_seed_2026
      finished in 3.06 min (183.7 sec)
  [2/3] Excretion__split_046__run_02_seed_2027
      finished in 1.37 min (82.2 sec)
  [3/3] Excretion__split_046__run_03_seed_2028
      finished in 1.91 min (114.6 sec)
Split Excretion__split_046 finished in 6.35 min (380.8 sec)
====================================================================================================
Running split: Excretion__split_047 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_047__run_01_seed_2026
      finished in 2.99 min (179.5 sec)
  [2/3] Excretion__split_047__run_02_seed_2027
      finished in 1.38 min (82.8 sec)
  [3/3] Excretion__split_047__run_03_seed_2028
      finished in 1.99 min (119.5 sec)
Split Excretion__split_047 finished in 6.37 min (382.0 sec)
====================================================================================================
Running split: Excretion__split_048 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_048__run_01_seed_2026
      finished in 3.03 min (181.7 sec)
  [2/3] Excretion__split_048__run_02_seed_2027
      finished in 3.07 min (184.5 sec)
  [3/3] Excretion__split_048__run_03_seed_2028
      finished in 2.47 min (148.2 sec)
Split Excretion__split_048 finished in 8.58 min (514.6 sec)
====================================================================================================
Running split: Excretion__split_049 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_049__run_01_seed_2026
      finished in 2.99 min (179.4 sec)
  [2/3] Excretion__split_049__run_02_seed_2027
      finished in 2.99 min (179.2 sec)
  [3/3] Excretion__split_049__run_03_seed_2028
      finished in 2.88 min (173.1 sec)
Split Excretion__split_049 finished in 8.86 min (531.9 sec)
====================================================================================================
Running split: Excretion__split_050 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_050__run_01_seed_2026
      finished in 2.82 min (168.9 sec)
  [2/3] Excretion__split_050__run_02_seed_2027
      finished in 1.36 min (81.8 sec)
  [3/3] Excretion__split_050__run_03_seed_2028
      finished in 1.92 min (115.1 sec)
Split Excretion__split_050 finished in 6.10 min (366.0 sec)
====================================================================================================
Running split: Excretion__split_051 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_051__run_01_seed_2026
      finished in 3.01 min (180.4 sec)
  [2/3] Excretion__split_051__run_02_seed_2027
      finished in 1.37 min (82.1 sec)
  [3/3] Excretion__split_051__run_03_seed_2028
      finished in 2.65 min (159.0 sec)
Split Excretion__split_051 finished in 7.03 min (421.7 sec)
====================================================================================================
Running split: Excretion__split_052 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_052__run_01_seed_2026
      finished in 3.02 min (181.1 sec)
  [2/3] Excretion__split_052__run_02_seed_2027
      finished in 2.43 min (145.9 sec)
  [3/3] Excretion__split_052__run_03_seed_2028

      finished in 2.97 min (178.2 sec)
Split Excretion__split_052 finished in 8.42 min (505.5 sec)
====================================================================================================
Running split: Excretion__split_053 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_053__run_01_seed_2026
      finished in 2.29 min (137.5 sec)
  [2/3] Excretion__split_053__run_02_seed_2027
      finished in 2.97 min (178.0 sec)
  [3/3] Excretion__split_053__run_03_seed_2028
      finished in 1.90 min (113.8 sec)
Split Excretion__split_053 finished in 7.16 min (429.4 sec)
====================================================================================================
Running split: Excretion__split_054 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_054__run_01_seed_2026
      finished in 2.97 min (178.2 sec)
  [2/3] Excretion__split_054__run_02_seed_2027
      finished in 2.97 min (178.0 sec)
  [3/3] Excretion__split_054__run_03_seed_2028
      finished in 2.97 min (178.2 sec)
Split Excretion__split_054 finished in 8.91 min (534.6 sec)
====================================================================================================
Running split: Excretion__split_055 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_055__run_01_seed_2026
      finished in 2.97 min (178.0 sec)
  [2/3] Excretion__split_055__run_02_seed_2027
      finished in 2.97 min (178.1 sec)
  [3/3] Excretion__split_055__run_03_seed_2028
      finished in 2.76 min (165.7 sec)
Split Excretion__split_055 finished in 8.70 min (522.0 sec)
====================================================================================================
Running split: Excretion__split_056 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_056__run_01_seed_2026
      finished in 2.80 min (168.1 sec)
  [2/3] Excretion__split_056__run_02_seed_2027
      finished in 2.97 min (178.0 sec)
  [3/3] Excretion__split_056__run_03_seed_2028
      finished in 1.90 min (114.1 sec)
Split Excretion__split_056 finished in 7.67 min (460.4 sec)
====================================================================================================
Running split: Excretion__split_057 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_057__run_01_seed_2026
      finished in 2.85 min (170.9 sec)
  [2/3] Excretion__split_057__run_02_seed_2027
      finished in 2.42 min (145.1 sec)
  [3/3] Excretion__split_057__run_03_seed_2028
      finished in 1.90 min (114.0 sec)
Split Excretion__split_057 finished in 7.17 min (430.0 sec)
====================================================================================================
Running split: Excretion__split_058 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_058__run_01_seed_2026
      finished in 2.97 min (178.1 sec)
  [2/3] Excretion__split_058__run_02_seed_2027
      finished in 1.36 min (81.4 sec)
  [3/3] Excretion__split_058__run_03_seed_2028
      finished in 1.90 min (114.1 sec)
Split Excretion__split_058 finished in 6.23 min (373.9 sec)
====================================================================================================
Running split: Excretion__split_059 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_059__run_01_seed_2026
      finished in 2.97 min (178.0 sec)
  [2/3] Excretion__split_059__run_02_seed_2027
      finished in 2.97 min (177.9 sec)
  [3/3] Excretion__split_059__run_03_seed_2028
      finished in 1.90 min (114.1 sec)
Split Excretion__split_059 finished in 7.84 min (470.3 sec)
====================================================================================================
Running split: Excretion__split_060 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_060__run_01_seed_2026
      finished in 2.85 min (171.0 sec)
  [2/3] Excretion__split_060__run_02_seed_2027
      finished in 2.41 min (144.5 sec)
  [3/3] Excretion__split_060__run_03_seed_2028
      finished in 1.90 min (114.2 sec)
Split Excretion__split_060 finished in 7.16 min (429.9 sec)
====================================================================================================
Running split: Excretion__split_061 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_061__run_01_seed_2026
      finished in 2.96 min (177.9 sec)
  [2/3] Excretion__split_061__run_02_seed_2027
      finished in 2.97 min (177.9 sec)
  [3/3] Excretion__split_061__run_03_seed_2028
      finished in 2.84 min (170.2 sec)
Split Excretion__split_061 finished in 8.77 min (526.2 sec)
====================================================================================================
Running split: Excretion__split_062 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_062__run_01_seed_2026
      finished in 2.29 min (137.3 sec)
  [2/3] Excretion__split_062__run_02_seed_2027
      finished in 2.41 min (144.7 sec)
  [3/3] Excretion__split_062__run_03_seed_2028
      finished in 1.90 min (114.0 sec)
Split Excretion__split_062 finished in 6.60 min (396.3 sec)
====================================================================================================
Running split: Excretion__split_063 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_063__run_01_seed_2026
      finished in 2.97 min (178.1 sec)
  [2/3] Excretion__split_063__run_02_seed_2027
      finished in 2.97 min (177.9 sec)
  [3/3] Excretion__split_063__run_03_seed_2028
      finished in 1.89 min (113.7 sec)
Split Excretion__split_063 finished in 7.83 min (469.9 sec)
====================================================================================================
Running split: Excretion__split_064 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_064__run_01_seed_2026
      finished in 2.96 min (177.5 sec)
  [2/3] Excretion__split_064__run_02_seed_2027
      finished in 2.96 min (177.7 sec)
  [3/3] Excretion__split_064__run_03_seed_2028
      finished in 2.97 min (178.2 sec)
Split Excretion__split_064 finished in 8.89 min (533.6 sec)
====================================================================================================
Running split: Excretion__split_065 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_065__run_01_seed_2026
      finished in 2.97 min (178.1 sec)
  [2/3] Excretion__split_065__run_02_seed_2027
      finished in 2.41 min (144.5 sec)
  [3/3] Excretion__split_065__run_03_seed_2028
      finished in 2.62 min (157.1 sec)
Split Excretion__split_065 finished in 8.00 min (480.0 sec)
====================================================================================================
Running split: Excretion__split_066 | process: Excretion
====================================================================================================

supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_066__run_01_seed_2026
      finished in 2.97 min (178.0 sec)
  [2/3] Excretion__split_066__run_02_seed_2027
      finished in 1.36 min (81.5 sec)
  [3/3] Excretion__split_066__run_03_seed_2028
      finished in 2.62 min (157.3 sec)
Split Excretion__split_066 finished in 6.95 min (416.9 sec)
====================================================================================================
Running split: Excretion__split_067 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_067__run_01_seed_2026
      finished in 2.80 min (168.2 sec)
  [2/3] Excretion__split_067__run_02_seed_2027
      finished in 1.36 min (81.4 sec)
  [3/3] Excretion__split_067__run_03_seed_2028
      finished in 1.90 min (114.2 sec)
Split Excretion__split_067 finished in 6.07 min (364.0 sec)
====================================================================================================
Running split: Excretion__split_068 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_068__run_01_seed_2026
      finished in 1.93 min (115.9 sec)
  [2/3] Excretion__split_068__run_02_seed_2027
      finished in 2.97 min (178.5 sec)
  [3/3] Excretion__split_068__run_03_seed_2028
      finished in 1.93 min (115.7 sec)
Split Excretion__split_068 finished in 6.84 min (410.3 sec)
====================================================================================================
Running split: Excretion__split_069 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_069__run_01_seed_2026
      finished in 2.98 min (178.8 sec)
  [2/3] Excretion__split_069__run_02_seed_2027
      finished in 2.96 min (177.5 sec)
  [3/3] Excretion__split_069__run_03_seed_2028
      finished in 1.92 min (115.3 sec)
Split Excretion__split_069 finished in 7.86 min (471.9 sec)
====================================================================================================
Running split: Excretion__split_070 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_070__run_01_seed_2026
      finished in 2.96 min (177.5 sec)
  [2/3] Excretion__split_070__run_02_seed_2027
      finished in 1.36 min (81.4 sec)
  [3/3] Excretion__split_070__run_03_seed_2028
      finished in 1.90 min (114.1 sec)
Split Excretion__split_070 finished in 6.22 min (373.3 sec)
====================================================================================================
Running split: Excretion__split_071 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_071__run_01_seed_2026
      finished in 2.69 min (161.7 sec)
  [2/3] Excretion__split_071__run_02_seed_2027
      finished in 2.97 min (178.2 sec)
  [3/3] Excretion__split_071__run_03_seed_2028
      finished in 1.90 min (114.0 sec)
Split Excretion__split_071 finished in 7.57 min (454.0 sec)
====================================================================================================
Running split: Excretion__split_072 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_072__run_01_seed_2026
      finished in 2.96 min (177.8 sec)
  [2/3] Excretion__split_072__run_02_seed_2027
      finished in 2.96 min (177.8 sec)
  [3/3] Excretion__split_072__run_03_seed_2028
      finished in 1.90 min (114.0 sec)
Split Excretion__split_072 finished in 7.83 min (469.8 sec)
====================================================================================================
Running split: Excretion__split_073 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_073__run_01_seed_2026
      finished in 2.97 min (178.0 sec)
  [2/3] Excretion__split_073__run_02_seed_2027
      finished in 2.96 min (177.9 sec)
  [3/3] Excretion__split_073__run_03_seed_2028
      finished in 2.77 min (165.9 sec)
Split Excretion__split_073 finished in 8.70 min (522.0 sec)
====================================================================================================
Running split: Excretion__split_074 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_074__run_01_seed_2026
      finished in 2.69 min (161.6 sec)
  [2/3] Excretion__split_074__run_02_seed_2027
      finished in 2.97 min (178.0 sec)
  [3/3] Excretion__split_074__run_03_seed_2028
      finished in 1.90 min (114.1 sec)
Split Excretion__split_074 finished in 7.56 min (453.8 sec)
====================================================================================================
Running split: Excretion__split_075 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_075__run_01_seed_2026
      finished in 2.97 min (177.9 sec)
  [2/3] Excretion__split_075__run_02_seed_2027
      finished in 2.99 min (179.3 sec)
  [3/3] Excretion__split_075__run_03_seed_2028
      finished in 1.89 min (113.6 sec)
Split Excretion__split_075 finished in 7.85 min (471.0 sec)
====================================================================================================
Running split: Excretion__split_076 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_076__run_01_seed_2026
      finished in 2.96 min (177.8 sec)
  [2/3] Excretion__split_076__run_02_seed_2027
      finished in 1.36 min (81.3 sec)
  [3/3] Excretion__split_076__run_03_seed_2028
      finished in 2.97 min (178.0 sec)
Split Excretion__split_076 finished in 7.29 min (437.3 sec)
====================================================================================================
Running split: Excretion__split_077 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_077__run_01_seed_2026
      finished in 2.96 min (177.4 sec)
  [2/3] Excretion__split_077__run_02_seed_2027
      finished in 1.36 min (81.3 sec)
  [3/3] Excretion__split_077__run_03_seed_2028
      finished in 1.92 min (115.4 sec)
Split Excretion__split_077 finished in 6.24 min (374.3 sec)
====================================================================================================
Running split: Excretion__split_078 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_078__run_01_seed_2026
      finished in 2.29 min (137.3 sec)
  [2/3] Excretion__split_078__run_02_seed_2027
      finished in 2.96 min (177.8 sec)
  [3/3] Excretion__split_078__run_03_seed_2028
      finished in 1.93 min (115.6 sec)
Split Excretion__split_078 finished in 7.18 min (430.8 sec)
====================================================================================================
Running split: Excretion__split_079 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_079__run_01_seed_2026
      finished in 2.96 min (177.7 sec)
  [2/3] Excretion__split_079__run_02_seed_2027
      finished in 2.96 min (177.7 sec)
  [3/3] Excretion__split_079__run_03_seed_2028

      finished in 1.90 min (114.1 sec)
Split Excretion__split_079 finished in 7.83 min (469.8 sec)
====================================================================================================
Running split: Excretion__split_080 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_080__run_01_seed_2026
      finished in 2.29 min (137.2 sec)
  [2/3] Excretion__split_080__run_02_seed_2027
      finished in 2.96 min (177.6 sec)
  [3/3] Excretion__split_080__run_03_seed_2028
      finished in 1.90 min (113.7 sec)
Split Excretion__split_080 finished in 7.14 min (428.6 sec)
====================================================================================================
Running split: Excretion__split_081 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_081__run_01_seed_2026
      finished in 2.96 min (177.8 sec)
  [2/3] Excretion__split_081__run_02_seed_2027
      finished in 2.96 min (177.7 sec)
  [3/3] Excretion__split_081__run_03_seed_2028
      finished in 1.91 min (114.4 sec)
Split Excretion__split_081 finished in 7.83 min (470.0 sec)
====================================================================================================
Running split: Excretion__split_082 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_082__run_01_seed_2026
      finished in 1.35 min (81.1 sec)
  [2/3] Excretion__split_082__run_02_seed_2027
      finished in 1.36 min (81.3 sec)
  [3/3] Excretion__split_082__run_03_seed_2028
      finished in 1.90 min (114.1 sec)
Split Excretion__split_082 finished in 4.61 min (276.6 sec)
====================================================================================================
Running split: Excretion__split_083 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_083__run_01_seed_2026
      finished in 2.80 min (167.8 sec)
  [2/3] Excretion__split_083__run_02_seed_2027
      finished in 1.35 min (81.3 sec)
  [3/3] Excretion__split_083__run_03_seed_2028
      finished in 1.90 min (113.9 sec)
Split Excretion__split_083 finished in 6.05 min (363.1 sec)
====================================================================================================
Running split: Excretion__split_084 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_084__run_01_seed_2026
      finished in 2.97 min (178.2 sec)
  [2/3] Excretion__split_084__run_02_seed_2027
      finished in 2.96 min (177.9 sec)
  [3/3] Excretion__split_084__run_03_seed_2028
      finished in 2.83 min (169.7 sec)
Split Excretion__split_084 finished in 8.76 min (525.9 sec)
====================================================================================================
Running split: Excretion__split_085 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_085__run_01_seed_2026
      finished in 2.80 min (167.8 sec)
  [2/3] Excretion__split_085__run_02_seed_2027
      finished in 2.96 min (177.8 sec)
  [3/3] Excretion__split_085__run_03_seed_2028
      finished in 1.90 min (114.0 sec)
Split Excretion__split_085 finished in 7.66 min (459.8 sec)
====================================================================================================
Running split: Excretion__split_086 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_086__run_01_seed_2026
      finished in 2.97 min (177.9 sec)
  [2/3] Excretion__split_086__run_02_seed_2027
      finished in 2.96 min (177.8 sec)
  [3/3] Excretion__split_086__run_03_seed_2028
      finished in 1.90 min (114.1 sec)
Split Excretion__split_086 finished in 7.83 min (469.9 sec)
====================================================================================================
Running split: Excretion__split_087 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_087__run_01_seed_2026
      finished in 2.97 min (178.0 sec)
  [2/3] Excretion__split_087__run_02_seed_2027
      finished in 2.96 min (177.8 sec)
  [3/3] Excretion__split_087__run_03_seed_2028
      finished in 2.97 min (178.2 sec)
Split Excretion__split_087 finished in 8.90 min (534.2 sec)
====================================================================================================
Running split: Excretion__split_088 | process: Excretion
====================================================================================================
      finished in 2.29 min (137.4 sec)
  [2/3] Excretion__split_088__run_02_seed_2027
      finished in 2.97 min (178.1 sec)
  [3/3] Excretion__split_088__run_03_seed_2028
      finished in 1.90 min (114.2 sec)
Split Excretion__split_088 finished in 7.16 min (429.9 sec)
====================================================================================================
Running split: Excretion__split_089 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_089__run_01_seed_2026
      finished in 2.96 min (177.7 sec)
  [2/3] Excretion__split_089__run_02_seed_2027
      finished in 2.96 min (177.5 sec)
  [3/3] Excretion__split_089__run_03_seed_2028
      finished in 1.90 min (113.7 sec)
Split Excretion__split_089 finished in 7.82 min (469.2 sec)
====================================================================================================
Running split: Excretion__split_090 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_090__run_01_seed_2026
      finished in 2.98 min (178.5 sec)
  [2/3] Excretion__split_090__run_02_seed_2027
      finished in 1.77 min (106.3 sec)
  [3/3] Excretion__split_090__run_03_seed_2028
      finished in 1.90 min (113.9 sec)
Split Excretion__split_090 finished in 6.65 min (398.9 sec)
====================================================================================================
Running split: Excretion__split_091 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_091__run_01_seed_2026
      finished in 2.84 min (170.6 sec)
  [2/3] Excretion__split_091__run_02_seed_2027
      finished in 2.96 min (177.7 sec)
  [3/3] Excretion__split_091__run_03_seed_2028
      finished in 1.90 min (114.0 sec)
Split Excretion__split_091 finished in 7.71 min (462.5 sec)
====================================================================================================
Running split: Excretion__split_092 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_092__run_01_seed_2026
      finished in 2.29 min (137.4 sec)
  [2/3] Excretion__split_092__run_02_seed_2027
      finished in 2.41 min (144.3 sec)
  [3/3] Excretion__split_092__run_03_seed_2028
      finished in 1.92 min (115.5 sec)
Split Excretion__split_092 finished in 6.62 min (397.4 sec)
====================================================================================================
Running split: Excretion__split_093 | process: Excretion
====================================================================================================

supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_093__run_01_seed_2026
      finished in 2.29 min (137.2 sec)
  [2/3] Excretion__split_093__run_02_seed_2027
      finished in 2.96 min (177.8 sec)
  [3/3] Excretion__split_093__run_03_seed_2028
      finished in 1.92 min (115.5 sec)
Split Excretion__split_093 finished in 7.18 min (430.8 sec)
====================================================================================================
Running split: Excretion__split_094 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_094__run_01_seed_2026
      finished in 2.97 min (178.0 sec)
  [2/3] Excretion__split_094__run_02_seed_2027
      finished in 2.96 min (177.5 sec)
  [3/3] Excretion__split_094__run_03_seed_2028
      finished in 2.62 min (157.2 sec)
Split Excretion__split_094 finished in 8.55 min (512.9 sec)
====================================================================================================
Running split: Excretion__split_095 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_095__run_01_seed_2026
      finished in 2.40 min (144.0 sec)
  [2/3] Excretion__split_095__run_02_seed_2027
      finished in 1.35 min (81.3 sec)
  [3/3] Excretion__split_095__run_03_seed_2028
      finished in 1.90 min (114.0 sec)
Split Excretion__split_095 finished in 5.66 min (339.4 sec)
====================================================================================================
Running split: Excretion__split_096 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_096__run_01_seed_2026
      finished in 2.97 min (178.1 sec)
  [2/3] Excretion__split_096__run_02_seed_2027
      finished in 2.96 min (177.8 sec)
  [3/3] Excretion__split_096__run_03_seed_2028
      finished in 1.90 min (114.2 sec)
Split Excretion__split_096 finished in 7.84 min (470.3 sec)
====================================================================================================
Running split: Excretion__split_097 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_097__run_01_seed_2026
      finished in 2.97 min (178.1 sec)
  [2/3] Excretion__split_097__run_02_seed_2027
      finished in 2.97 min (178.2 sec)
  [3/3] Excretion__split_097__run_03_seed_2028
      finished in 1.93 min (115.8 sec)
Split Excretion__split_097 finished in 7.87 min (472.3 sec)
====================================================================================================
Running split: Excretion__split_098 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_098__run_01_seed_2026
      finished in 2.98 min (178.7 sec)
  [2/3] Excretion__split_098__run_02_seed_2027
      finished in 2.96 min (177.8 sec)
  [3/3] Excretion__split_098__run_03_seed_2028
      finished in 2.97 min (177.9 sec)
Split Excretion__split_098 finished in 8.91 min (534.6 sec)
====================================================================================================
Running split: Excretion__split_099 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_099__run_01_seed_2026
      finished in 2.29 min (137.3 sec)
  [2/3] Excretion__split_099__run_02_seed_2027
      finished in 2.97 min (178.0 sec)
  [3/3] Excretion__split_099__run_03_seed_2028
      finished in 1.90 min (114.3 sec)
Split Excretion__split_099 finished in 7.16 min (429.7 sec)
====================================================================================================
Running split: Excretion__split_100 | process: Excretion
====================================================================================================
supervised seeds: 36
heldout genes: 3
  [1/3] Excretion__split_100__run_01_seed_2026
      finished in 2.70 min (161.8 sec)
  [2/3] Excretion__split_100__run_02_seed_2027
      finished in 2.97 min (178.5 sec)
  [3/3] Excretion__split_100__run_03_seed_2028
      finished in 1.90 min (113.9 sec)
Split Excretion__split_100 finished in 7.57 min (454.3 sec)
====================================================================================================
Running split: Uptake__split_001 | process: Uptake
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Uptake__split_001__run_01_seed_2026
      finished in 1.36 min (81.3 sec)
  [2/3] Uptake__split_001__run_02_seed_2027
      finished in 2.41 min (144.5 sec)
  [3/3] Uptake__split_001__run_03_seed_2028
      finished in 1.90 min (114.3 sec)
Split Uptake__split_001 finished in 5.67 min (340.3 sec)
====================================================================================================
Running split: Uptake__split_002 | process: Uptake
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Uptake__split_002__run_01_seed_2026
      finished in 2.97 min (178.1 sec)
  [2/3] Uptake__split_002__run_02_seed_2027
      finished in 1.77 min (106.3 sec)
  [3/3] Uptake__split_002__run_03_seed_2028
      finished in 1.90 min (114.0 sec)
Split Uptake__split_002 finished in 6.64 min (398.6 sec)
====================================================================================================
Running split: Uptake__split_003 | process: Uptake
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Uptake__split_003__run_01_seed_2026
      finished in 2.80 min (167.9 sec)
  [2/3] Uptake__split_003__run_02_seed_2027
      finished in 2.99 min (179.5 sec)
  [3/3] Uptake__split_003__run_03_seed_2028
      finished in 2.96 min (177.9 sec)
Split Uptake__split_003 finished in 8.76 min (525.5 sec)
====================================================================================================
Running split: Uptake__split_004 | process: Uptake
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Uptake__split_004__run_01_seed_2026
      finished in 2.97 min (178.1 sec)
  [2/3] Uptake__split_004__run_02_seed_2027
      finished in 2.96 min (177.9 sec)
  [3/3] Uptake__split_004__run_03_seed_2028
      finished in 1.90 min (113.9 sec)
Split Uptake__split_004 finished in 7.83 min (470.0 sec)
====================================================================================================
Running split: Uptake__split_005 | process: Uptake
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Uptake__split_005__run_01_seed_2026
      finished in 2.80 min (167.7 sec)
  [2/3] Uptake__split_005__run_02_seed_2027
      finished in 1.77 min (106.3 sec)
  [3/3] Uptake__split_005__run_03_seed_2028
      finished in 1.51 min (90.7 sec)
Split Uptake__split_005 finished in 6.08 min (364.9 sec)
====================================================================================================
Running split: Uptake__split_006 | process: Uptake
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Uptake__split_006__run_01_seed_2026
      finished in 2.96 min (177.9 sec)
  [2/3] Uptake__split_006__run_02_seed_2027
      finished in 1.78 min (106.8 sec)
  [3/3] Uptake__split_006__run_03_seed_2028
      finished in 1.90 min (113.9 sec)
Split Uptake__split_006 finished in 6.65 min (398.8 sec)
====================================================================================================
Running split: Uptake__split_007 | process: Uptake
====================================================================================================

supervised seeds: 38
heldout genes: 1
  [1/3] Uptake__split_007__run_01_seed_2026
      finished in 2.79 min (167.6 sec)
  [2/3] Uptake__split_007__run_02_seed_2027
      finished in 2.96 min (177.8 sec)
  [3/3] Uptake__split_007__run_03_seed_2028
      finished in 1.89 min (113.6 sec)
Split Uptake__split_007 finished in 7.65 min (459.2 sec)
====================================================================================================
Running split: Uptake__split_008 | process: Uptake
====================================================================================================
supervised seeds: 38
heldout genes: 1
  [1/3] Uptake__split_008__run_01_seed_2026
      finished in 2.80 min (167.9 sec)
  [2/3] Uptake__split_008__run_02_seed_2027
      finished in 2.97 min (178.0 sec)
  [3/3] Uptake__split_008__run_03_seed_2028
      finished in 1.90 min (114.2 sec)
Split Uptake__split_008 finished in 7.67 min (460.2 sec)
saved:
D:\phd cases\metabolic analysis\code\Deep_GLOC\run_GAT_new\masked_seed_benchmark\deep_gloc_benchmark_results_all214_run3\metrics\deep_gloc_split_metrics.tsv
D:\phd cases\metabolic analysis\code\Deep_GLOC\run_GAT_new\masked_seed_benchmark\deep_gloc_benchmark_results_all214_run3\metrics\deep_gloc_all_heldout_ranks.tsv

,split_id,process,split_elapsed_sec,split_elapsed_min,n_candidates,n_heldout,n_negatives,Recall@20,Recall@50,Recall@100,median_rank,MRR,AUROC,AUPRC
0,Biosynthesis__split_001,Biosynthesis,881.666543,14.694442,3176,4,3172,0.25,1.00,1.0,37.0,0.034860,0.990227,0.071869
1,Biosynthesis__split_002,Biosynthesis,952.712492,15.878542,3176,4,3172,0.75,1.00,1.0,8.5,0.362060,0.997557,0.513716
2,Biosynthesis__split_003,Biosynthesis,893.568536,14.892809,3176,4,3172,0.50,0.75,1.0,23.5,0.086263,0.989124,0.142372
3,Biosynthesis__split_004,Biosynthesis,732.286226,12.204770,3176,4,3172,0.25,0.75,1.0,38.5,0.037429,0.989360,0.070037
4,Biosynthesis__split_005,Biosynthesis,1089.363759,18.156063,3176,4,3172,0.50,0.75,1.0,28.0,0.111772,0.991882,0.155423

In [11]:
# ============================================================
# 11. 按 process 汇总
# ============================================================
metric_cols = ["Recall@20", "Recall@50", "Recall@100", "median_rank", "MRR", "AUROC", "AUPRC"]

process_summary_df = (
    split_metrics_df.groupby("process")[metric_cols]
    .agg(["mean", "std", "median", "count"])
)

# 拉平列名
process_summary_df.columns = [f"{a}__{b}" for a, b in process_summary_df.columns]
process_summary_df = process_summary_df.reset_index()

process_summary_file = os.path.join(METRIC_DIR, "deep_gloc_process_summary.tsv")
process_summary_df.to_csv(process_summary_file, sep="\t", index=False)

print("saved:", process_summary_file)
display(process_summary_df)

saved: D:\phd cases\metabolic analysis\code\Deep_GLOC\run_GAT_new\masked_seed_benchmark\deep_gloc_benchmark_results_all214_run3\metrics\deep_gloc_process_summary.tsv

,process,Recall@20__mean,Recall@20__std,Recall@20__median,Recall@20__count,Recall@50__mean,Recall@50__std,Recall@50__median,Recall@50__count,Recall@100__mean,...,MRR__median,MRR__count,AUROC__mean,AUROC__std,AUROC__median,AUROC__count,AUPRC__mean,AUPRC__std,AUPRC__median,AUPRC__count
0,Biosynthesis,0.632500,0.247347,0.750000,100,0.885000,0.156589,1.000000,100,0.967500,...,0.132409,100,0.986854,0.052479,0.994168,100,0.274465,0.201639,0.206429,100
1,Esterification,0.500000,0.547723,0.500000,6,0.833333,0.408248,1.000000,6,1.000000,...,0.177305,6,0.991173,0.009873,0.992434,6,0.398119,0.481907,0.177305,6
2,Excretion,0.716667,0.269576,0.666667,100,0.753333,0.239809,0.666667,100,0.793333,...,0.246096,100,0.899158,0.125177,0.963377,100,0.376207,0.216420,0.361111,100
3,Uptake,0.750000,0.462910,1.000000,8,0.750000,0.462910,1.000000,8,0.750000,...,1.000000,8,0.840558,0.351861,1.000000,8,0.750180,0.462576,1.000000,8

In [12]:
# ============================================================
# 12. macro-average（四个 process 等权）
# ============================================================
# 这里不是把所有 split 混在一起平均，而是先按 process 求均值，再对 process 做平均
process_means_df = (
    split_metrics_df.groupby("process")[metric_cols]
    .mean()
    .reset_index()
)

macro_row = {"level": "macro_average"}
for c in metric_cols:
    macro_row[c] = process_means_df[c].mean()

macro_df = pd.DataFrame([macro_row])

macro_file = os.path.join(METRIC_DIR, "deep_gloc_macro_average.tsv")
macro_df.to_csv(macro_file, sep="\t", index=False)

print("saved:", macro_file)
display(macro_df)

saved: D:\phd cases\metabolic analysis\code\Deep_GLOC\run_GAT_new\masked_seed_benchmark\deep_gloc_benchmark_results_all214_run3\metrics\deep_gloc_macro_average.tsv

,level,Recall@20,Recall@50,Recall@100,median_rank,MRR,AUROC,AUPRC
0,macro_average,0.649792,0.805417,0.877708,151.12125,0.39852,0.929436,0.449743

## 结果解释建议

### 1. 每个 split 的指标
`deep_gloc_split_metrics.tsv`  
这是最底层 benchmark 结果。

### 2. 每个 process 的平均结果
`deep_gloc_process_summary.tsv`  
建议用于和 RWR / DeepWalk 做 process 内比较。

### 3. macro-average
`deep_gloc_macro_average.tsv`  
建议作为四个过程整体表现的主结果，因为它不会让 split 多的过程权重更大。

## 和师弟结果合并时
后续你只需要把师弟的 RWR / DeepWalk 结果也整理成同样的 split-level metrics 表，再按：
- `process`
- `split_id`
- `method`

合并即可。

###保存环境数据
import os
import dill
import json
import types
from datetime import datetime

save_dir = f"session_backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
os.makedirs(save_dir, exist_ok=True)

skip_names = {
    "In", "Out", "exit", "quit", "get_ipython"
}

saved = {}
skipped = {}

for k, v in list(globals().items()):
    if k.startswith("_") or k in skip_names:
        continue
    if isinstance(v, (
        types.ModuleType,
        types.FunctionType,
        types.BuiltinFunctionType,
        type
    )):
        skipped[k] = "module/function/class"
        continue

    try:
        dill.dumps(v)
        saved[k] = v
    except Exception as e:
        skipped[k] = str(e)

workspace_file = os.path.join(save_dir, "workspace.pkl")
with open(workspace_file, "wb") as f:
    dill.dump(saved, f)

with open(os.path.join(save_dir, "saved_names.json"), "w", encoding="utf-8") as f:
    json.dump(sorted(saved.keys()), f, ensure_ascii=False, indent=2)

with open(os.path.join(save_dir, "skipped_names.json"), "w", encoding="utf-8") as f:
    json.dump(skipped, f, ensure_ascii=False, indent=2)

print(f"保存完成: {workspace_file}")
print(f"成功保存变量数: {len(saved)}")
print(f"跳过变量数: {len(skipped)}")
print("已保存变量示例:", list(saved.keys())[:20])

import json
with open("D:/phd cases/metabolic analysis/code/Deep_GLOC/run_GAT_new/masked_seed_benchmark/deep_gloc_benchmark_results_all214_run3/session_backup_20260322_134348/saved_names.json", "r", encoding="utf-8") as f:
    saved_names = json.load(f)

print(saved_names)

print(type(res))
print(res.keys() if isinstance(res, dict) else "res is not a dict")